libutap: builder.h File Reference
builder.h File Reference
#include <cstdio>
#include <stdexcept>
#include <string>
#include <boost/format.hpp>
#include "utap/common.h"
Classes
class UTAP::TypeException
Exception indicating a type error.
class UTAP::ParserBuilder
The ParserBuilder interface is used by the parser to output the parsed system.
Namespaces
UTAP
Functions
int32_t parseXTA (FILE *, UTAP::ParserBuilder *, bool newxta)
Parse a file in the XTA format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
int32_t parseXTA (const char *, UTAP::ParserBuilder *, bool newxta)
int32_t parseXTA (const char *, UTAP::ParserBuilder *, bool newxta, UTAP::xta_part_t part, std::string xpath)
Parse a buffer in the XTA format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
int32_t parseXMLBuffer (const char *buffer, UTAP::ParserBuilder *, bool newxta)
Parse a buffer in the XML format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
int32_t parseXMLFile (const char *filename, UTAP::ParserBuilder *, bool newxta)
Parse the file with the given name assuming it is in the XML format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
int32_t parseProperty (const char *str, UTAP::ParserBuilder *aParserBuilder, const std::string &xpath="")
Parse properties from a buffer.
int32_t parseProperty (FILE *, UTAP::ParserBuilder *aParserBuilder)
Parse properties from a file.
Function Documentation
int32_t parseProperty (const char * str, UTAP::ParserBuilder * aParserBuilder, const std::string & xpath = "")
Parse properties from a buffer.
The properties are reported using the given ParserBuilder and errors are reported using the ErrorHandler.
References parseProperty(), utap__delete_buffer(), utap__scan_string(), and YY_CURRENT_BUFFER.
int32_t parseProperty (FILE * , UTAP::ParserBuilder * aParserBuilder)
Parse properties from a file.
The properties are reported using the given ParserBuilder and errors are reported using the ErrorHandler.
References parseProperty(), utap__create_buffer(), utap__delete_buffer(), utap__switch_to_buffer(), YY_BUF_SIZE, and YY_CURRENT_BUFFER.
int32_t parseXMLBuffer (const char * buffer, UTAP::ParserBuilder * , bool newxta)
Parse a buffer in the XML format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
If newxta is true, then the 4.x syntax is used; otherwise the 3.x syntax is used. On success, this function returns with a positive value.
int32_t parseXMLFile (const char * filename, UTAP::ParserBuilder * , bool newxta)
Parse the file with the given name assuming it is in the XML format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
If newxta is true, then the 4.x syntax is used; otherwise the 3.x syntax is used. On success, this function returns with a positive value.
int32_t parseXTA (FILE * , UTAP::ParserBuilder * , bool newxta)
Parse a file in the XTA format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
If newxta is true, then the 4.x syntax is used; otherwise the 3.x syntax is used. On success, this function returns with a positive value.
References parseXTA(), UTAP::S_XTA, utap__create_buffer(), utap__delete_buffer(), utap__switch_to_buffer(), YY_BUF_SIZE, and YY_CURRENT_BUFFER.
int32_t parseXTA (const char * , UTAP::ParserBuilder * , bool newxta)
References parseXTA(), and UTAP::S_XTA.
int32_t parseXTA (const char * , UTAP::ParserBuilder * , bool newxta, UTAP::xta_part_t part, std::string xpath)
Parse a buffer in the XTA format, reporting the system to the given implementation of the the ParserBuilder interface and reporting errors to the ErrorHandler.
If newxta is true, then the 4.x syntax is used; otherwise the 3.x syntax is used. On success, this function returns with a positive value.
References parseXTA(), utap__delete_buffer(), utap__scan_string(), and YY_CURRENT_BUFFER.