libutap: UTAP::Statement Class Reference
UTAP::Statement Class Reference abstract
#include <statement.h>
Public Member Functions
virtual ~Statement ()
virtual int32_t accept (StatementVisitor *visitor)=0
virtual bool returns ()=0
virtual std::string toString (std::string prefix) const =0
Protected Member Functions
Statement ()
Constructor & Destructor Documentation
virtual UTAP::Statement::~Statement () inline virtual
Statement::Statement () protected
Member Function Documentation
virtual int32_t UTAP::Statement::accept (StatementVisitor * visitor) pure virtual
Implemented in UTAP::ReturnStatement, UTAP::ContinueStatement, UTAP::BreakStatement, UTAP::IfStatement, UTAP::DefaultStatement, UTAP::CaseStatement, UTAP::SwitchStatement, UTAP::BlockStatement, UTAP::DoWhileStatement, UTAP::WhileStatement, UTAP::IterationStatement, UTAP::ForStatement, UTAP::AssertStatement, UTAP::ExprStatement, and UTAP::EmptyStatement.
Referenced by UTAP::TypeChecker::checkDynamicExpressions(), UTAP::TypeChecker::visitDoWhileStatement(), UTAP::SignalFlow::visitDoWhileStatement(), UTAP::AbstractStatementVisitor::visitDoWhileStatement(), UTAP::ExpressionVisitor::visitDoWhileStatement(), UTAP::TypeChecker::visitForStatement(), UTAP::SignalFlow::visitForStatement(), UTAP::AbstractStatementVisitor::visitForStatement(), UTAP::ExpressionVisitor::visitForStatement(), UTAP::TypeChecker::visitIfStatement(), UTAP::SignalFlow::visitIfStatement(), UTAP::AbstractStatementVisitor::visitIfStatement(), UTAP::ExpressionVisitor::visitIfStatement(), UTAP::TypeChecker::visitIterationStatement(), UTAP::SignalFlow::visitIterationStatement(), UTAP::AbstractStatementVisitor::visitIterationStatement(), UTAP::TypeChecker::visitWhileStatement(), UTAP::SignalFlow::visitWhileStatement(), UTAP::AbstractStatementVisitor::visitWhileStatement(), and UTAP::ExpressionVisitor::visitWhileStatement().
virtual bool UTAP::Statement::returns () pure virtual
Implemented in UTAP::ReturnStatement, UTAP::ContinueStatement, UTAP::BreakStatement, UTAP::IfStatement, UTAP::DefaultStatement, UTAP::CaseStatement, UTAP::SwitchStatement, UTAP::BlockStatement, UTAP::DoWhileStatement, UTAP::WhileStatement, UTAP::IterationStatement, UTAP::ForStatement, UTAP::AssertStatement, UTAP::ExprStatement, and UTAP::EmptyStatement.
Referenced by UTAP::DoWhileStatement::returns(), UTAP::BlockStatement::returns(), and UTAP::IfStatement::returns().
virtual std::string UTAP::Statement::toString (std::string prefix) const pure virtual
Implemented in UTAP::ReturnStatement, UTAP::ContinueStatement, UTAP::BreakStatement, UTAP::IfStatement, UTAP::CaseStatement, UTAP::SwitchStatement, UTAP::BlockStatement, UTAP::DoWhileStatement, UTAP::WhileStatement, UTAP::IterationStatement, UTAP::ForStatement, UTAP::AssertStatement, UTAP::ExprStatement, and UTAP::EmptyStatement.
Referenced by UTAP::ForStatement::toString(), UTAP::IterationStatement::toString(), UTAP::WhileStatement::toString(), UTAP::DoWhileStatement::toString(), and UTAP::IfStatement::toString().
The documentation for this class was generated from the following files:
statement.h
statement.cpp