libutap: UTAP::AbstractStatementVisitor Class Reference
UTAP::AbstractStatementVisitor Class Reference
#include <statement.h>
Public Member Functions
virtual int32_t visitEmptyStatement (EmptyStatement *stat)
virtual int32_t visitExprStatement (ExprStatement *stat)
virtual int32_t visitAssertStatement (AssertStatement *stat)
virtual int32_t visitForStatement (ForStatement *stat)
virtual int32_t visitIterationStatement (IterationStatement *stat)
virtual int32_t visitWhileStatement (WhileStatement *stat)
virtual int32_t visitDoWhileStatement (DoWhileStatement *stat)
virtual int32_t visitBlockStatement (BlockStatement *stat)
virtual int32_t visitSwitchStatement (SwitchStatement *stat)
virtual int32_t visitCaseStatement (CaseStatement *stat)
virtual int32_t visitDefaultStatement (DefaultStatement *stat)
virtual int32_t visitIfStatement (IfStatement *stat)
virtual int32_t visitBreakStatement (BreakStatement *stat)
virtual int32_t visitContinueStatement (ContinueStatement *stat)
virtual int32_t visitReturnStatement (ReturnStatement *stat)
Public Member Functions inherited from UTAP::StatementVisitor
virtual ~StatementVisitor ()
Protected Member Functions
virtual int32_t visitStatement (Statement *stat)
Member Function Documentation
int32_t AbstractStatementVisitor::visitAssertStatement (AssertStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References visitStatement().
int32_t AbstractStatementVisitor::visitBlockStatement (BlockStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References UTAP::BlockStatement::begin(), and UTAP::BlockStatement::end().
Referenced by visitCaseStatement(), visitDefaultStatement(), and visitSwitchStatement().
int32_t AbstractStatementVisitor::visitBreakStatement (BreakStatement * stat) virtual
Implements UTAP::StatementVisitor.
References visitStatement().
int32_t AbstractStatementVisitor::visitCaseStatement (CaseStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor.
References visitBlockStatement().
int32_t AbstractStatementVisitor::visitContinueStatement (ContinueStatement * stat) virtual
Implements UTAP::StatementVisitor.
References visitStatement().
int32_t AbstractStatementVisitor::visitDefaultStatement (DefaultStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor.
References visitBlockStatement().
int32_t AbstractStatementVisitor::visitDoWhileStatement (DoWhileStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References UTAP::Statement::accept(), and UTAP::DoWhileStatement::stat.
int32_t AbstractStatementVisitor::visitEmptyStatement (EmptyStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::TypeChecker.
References visitStatement().
int32_t AbstractStatementVisitor::visitExprStatement (ExprStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References visitStatement().
int32_t AbstractStatementVisitor::visitForStatement (ForStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References UTAP::Statement::accept(), and UTAP::ForStatement::stat.
int32_t AbstractStatementVisitor::visitIfStatement (IfStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References UTAP::Statement::accept(), UTAP::IfStatement::falseCase, and UTAP::IfStatement::trueCase.
int32_t AbstractStatementVisitor::visitIterationStatement (IterationStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::TypeChecker.
References UTAP::Statement::accept(), and UTAP::IterationStatement::stat.
int32_t AbstractStatementVisitor::visitReturnStatement (ReturnStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References visitStatement().
int32_t AbstractStatementVisitor::visitStatement (Statement * stat) protected virtual
Referenced by visitAssertStatement(), visitBreakStatement(), visitContinueStatement(), visitEmptyStatement(), visitExprStatement(), and visitReturnStatement().
int32_t AbstractStatementVisitor::visitSwitchStatement (SwitchStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor.
References visitBlockStatement().
int32_t AbstractStatementVisitor::visitWhileStatement (WhileStatement * stat) virtual
Implements UTAP::StatementVisitor.
Reimplemented in UTAP::ExpressionVisitor, and UTAP::TypeChecker.
References UTAP::Statement::accept(), and UTAP::WhileStatement::stat.
The documentation for this class was generated from the following files:
statement.h
statement.cpp