libutap: UTAP::CompileTimeComputableValues Class Reference
UTAP::CompileTimeComputableValues Class Reference
Visitor which collects all compile time computable symbols.
#include <typechecker.h>
Public Member Functions
virtual void visitVariable (variable_t &)
virtual void visitInstance (instance_t &)
bool contains (symbol_t) const
Public Member Functions inherited from UTAP::SystemVisitor
virtual ~SystemVisitor ()
virtual void visitSystemBefore (TimedAutomataSystem *)
virtual void visitSystemAfter (TimedAutomataSystem *)
virtual bool visitTemplateBefore (template_t &)
virtual void visitTemplateAfter (template_t &)
virtual void visitState (state_t &)
virtual void visitEdge (edge_t &)
virtual void visitProcess (instance_t &)
virtual void visitFunction (function_t &)
virtual void visitTypeDef (symbol_t)
virtual void visitIODecl (iodecl_t &)
virtual void visitProgressMeasure (progress_t &)
virtual void visitGanttChart (gantt_t &)
virtual void visitInstanceLine (instanceLine_t &)
virtual void visitMessage (message_t &)
virtual void visitCondition (condition_t &)
virtual void visitUpdate (update_t &)
Detailed Description
Visitor which collects all compile time computable symbols.
These are all global and template local constants and all constant non-reference template parameters. Variables with mixed storage are not considered compile time computable.
Member Function Documentation
bool CompileTimeComputableValues::contains (symbol_t symbol) const
References variables.
void CompileTimeComputableValues::visitInstance (instance_t & temp) virtual
Reimplemented from UTAP::SystemVisitor.
References UTAP::frame_t::getSize(), UTAP::type_t::is(), UTAP::type_t::isConstant(), UTAP::type_t::isDouble(), UTAP::instance_t::parameters, UTAP::Constants::REF, and variables.
void CompileTimeComputableValues::visitVariable (variable_t & variable) virtual
Reimplemented from UTAP::SystemVisitor.
References UTAP::symbol_t::getType(), UTAP::type_t::isConstant(), UTAP::variable_t::uid, and variables.
The documentation for this class was generated from the following files:
typechecker.h
typechecker.cpp