libutap: UTAP::IterationStatement Class Reference
UTAP::IterationStatement Class Reference
Statement class for the iterator loop-construction.
#include <statement.h>
Public Member Functions
IterationStatement (symbol_t, frame_t, Statement *)
frame_t getFrame ()
virtual int32_t accept (StatementVisitor *visitor)
virtual bool returns ()
std::string toString (std::string prefix) const
Public Member Functions inherited from UTAP::Statement
virtual ~Statement ()
Public Attributes
symbol_t symbol
Statement * stat
Protected Attributes
frame_t frame
Additional Inherited Members
Protected Member Functions inherited from UTAP::Statement
Statement ()
Detailed Description
Statement class for the iterator loop-construction.
Constructor & Destructor Documentation
IterationStatement::IterationStatement (symbol_t sym, frame_t f, Statement * s)
References frame, stat, and symbol.
Member Function Documentation
int32_t IterationStatement::accept (StatementVisitor * visitor) virtual
Implements UTAP::Statement.
References UTAP::StatementVisitor::visitIterationStatement().
frame_t UTAP::IterationStatement::getFrame () inline
References frame.
bool IterationStatement::returns () virtual
Implements UTAP::Statement.
string IterationStatement::toString (std::string prefix) const virtual
Implements UTAP::Statement.
References UTAP::type_t::getLabel(), UTAP::symbol_t::getName(), UTAP::symbol_t::getType(), INDENT, stat, symbol, and UTAP::Statement::toString().
Member Data Documentation
frame_t UTAP::IterationStatement::frame protected
Referenced by getFrame(), and IterationStatement().
Statement* UTAP::IterationStatement::stat
Referenced by IterationStatement(), toString(), UTAP::TypeChecker::visitIterationStatement(), UTAP::SignalFlow::visitIterationStatement(), and UTAP::AbstractStatementVisitor::visitIterationStatement().
symbol_t UTAP::IterationStatement::symbol
Referenced by IterationStatement(), toString(), and UTAP::TypeChecker::visitIterationStatement().
The documentation for this class was generated from the following files:
statement.h
statement.cpp