libutap: UTAP::ExpressionVisitor Class Reference
UTAP::ExpressionVisitor Class Reference abstract
#include <statement.h>
Public Member Functions
virtual int32_t visitExprStatement (ExprStatement *stat)
virtual int32_t visitAssertStatement (AssertStatement *stat)
virtual int32_t visitForStatement (ForStatement *stat)
virtual int32_t visitWhileStatement (WhileStatement *stat)
virtual int32_t visitDoWhileStatement (DoWhileStatement *stat)
virtual int32_t visitBlockStatement (BlockStatement *stat)
virtual int32_t visitSwitchStatement (SwitchStatement *stat)
virtual int32_t visitCaseStatement (CaseStatement *stat)
virtual int32_t visitDefaultStatement (DefaultStatement *stat)
virtual int32_t visitIfStatement (IfStatement *stat)
virtual int32_t visitReturnStatement (ReturnStatement *stat)
Public Member Functions inherited from UTAP::AbstractStatementVisitor
virtual int32_t visitEmptyStatement (EmptyStatement *stat)
virtual int32_t visitIterationStatement (IterationStatement *stat)
virtual int32_t visitBreakStatement (BreakStatement *stat)
virtual int32_t visitContinueStatement (ContinueStatement *stat)
Public Member Functions inherited from UTAP::StatementVisitor
virtual ~StatementVisitor ()
Protected Member Functions
virtual void visitExpression (expression_t)=0
Protected Member Functions inherited from UTAP::AbstractStatementVisitor
virtual int32_t visitStatement (Statement *stat)
Member Function Documentation
int32_t ExpressionVisitor::visitAssertStatement (AssertStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::AssertStatement::expr, and visitExpression().
int32_t ExpressionVisitor::visitBlockStatement (BlockStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::BlockStatement::begin(), UTAP::BlockStatement::end(), UTAP::BlockStatement::getFrame(), UTAP::frame_t::getSize(), and visitExpression().
Referenced by visitCaseStatement(), visitDefaultStatement(), and visitSwitchStatement().
int32_t ExpressionVisitor::visitCaseStatement (CaseStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::CaseStatement::cond, visitBlockStatement(), and visitExpression().
int32_t ExpressionVisitor::visitDefaultStatement (DefaultStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References visitBlockStatement().
int32_t ExpressionVisitor::visitDoWhileStatement (DoWhileStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::Statement::accept(), UTAP::DoWhileStatement::cond, UTAP::DoWhileStatement::stat, and visitExpression().
virtual void UTAP::ExpressionVisitor::visitExpression (expression_t) protected pure virtual
Implemented in UTAP::CollectDynamicExpressions, UTAP::CollectDependenciesVisitor, and UTAP::CollectChangesVisitor.
Referenced by visitAssertStatement(), visitBlockStatement(), visitCaseStatement(), visitDoWhileStatement(), visitExprStatement(), visitForStatement(), visitIfStatement(), visitReturnStatement(), visitSwitchStatement(), and visitWhileStatement().
int32_t ExpressionVisitor::visitExprStatement (ExprStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::ExprStatement::expr, and visitExpression().
int32_t ExpressionVisitor::visitForStatement (ForStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::Statement::accept(), UTAP::ForStatement::cond, UTAP::ForStatement::init, UTAP::ForStatement::stat, UTAP::ForStatement::step, and visitExpression().
int32_t ExpressionVisitor::visitIfStatement (IfStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::Statement::accept(), UTAP::IfStatement::cond, UTAP::IfStatement::falseCase, UTAP::IfStatement::trueCase, and visitExpression().
int32_t ExpressionVisitor::visitReturnStatement (ReturnStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::ReturnStatement::value, and visitExpression().
int32_t ExpressionVisitor::visitSwitchStatement (SwitchStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::SwitchStatement::cond, visitBlockStatement(), and visitExpression().
int32_t ExpressionVisitor::visitWhileStatement (WhileStatement * stat) virtual
Reimplemented from UTAP::AbstractStatementVisitor.
References UTAP::Statement::accept(), UTAP::WhileStatement::cond, UTAP::WhileStatement::stat, and visitExpression().
The documentation for this class was generated from the following files:
statement.h
statement.cpp