libutap: UTAP::SystemBuilder Class Reference
UTAP::SystemBuilder Class Reference
This class constructs a TimedAutomataSystem.
#include <systembuilder.h>
Public Member Functions
SystemBuilder (TimedAutomataSystem *)
virtual void ganttDeclStart (const char *name)
virtual void ganttDeclSelect (const char *id)
virtual void ganttDeclEnd ()
virtual void ganttEntryStart ()
virtual void ganttEntrySelect (const char *id)
virtual void ganttEntryEnd ()
virtual void declProgress (bool)
Guard progress measure declaration.
virtual void procBegin (const char *name, const bool isTA=true, const std::string type="", const std::string mode="")
virtual void procEnd ()
virtual void procState (const char *name, bool hasInvariant, bool hasER)
Add a state to the current template.
virtual void procStateCommit (const char *name)
virtual void procStateUrgent (const char *name)
virtual void procStateInit (const char *name)
virtual void procBranchpoint (const char *name)
virtual void procEdgeBegin (const char *from, const char *to, const bool control, const char *actname)
virtual void procEdgeEnd (const char *from=0, const char *to=0)
virtual void procSelect (const char *id)
virtual void procGuard ()
virtual void procSync (Constants::synchronisation_t type)
virtual void procUpdate ()
virtual void procProb ()
virtual void instantiationBegin (const char *, size_t, const char *)
virtual void instantiationEnd (const char *, size_t, const char *, size_t)
virtual void process (const char *)
virtual void processListEnd ()
virtual void done ()
virtual void beforeUpdate ()
virtual void afterUpdate ()
virtual void beginChanPriority ()
virtual void addChanPriority (char separator)
virtual void defaultChanPriority ()
virtual void incProcPriority ()
virtual void procPriority (const char *)
virtual void procInstanceLine ()
Adds an instance line to the current template.
virtual void instanceName (const char *name, bool templ=true)
templ is true if the name of the instance contains parameters like "Train(1)".
virtual void instanceNameBegin (const char *name)
virtual void instanceNameEnd (const char *name, size_t arguments)
virtual void procMessage (const char *from, const char *to, const int loc, const bool pch)
Add a message to the current template.
virtual void procMessage (Constants::synchronisation_t type)
virtual void procCondition (const std::vector< char * > anchors, const int loc, const bool pch, const bool hot)
virtual void procCondition ()
virtual void procLscUpdate (const char *anchor, const int loc, const bool pch)
Add an update to the current template.
virtual void procLscUpdate ()
virtual void hasPrechart (const bool pch)
virtual void exprSync (Constants::synchronisation_t type)
virtual void declIO (const char *, int, int)
virtual void declDynamicTemplate (std::string)
Dynamic.
virtual void queryBegin ()
Verification queries.
virtual void queryFormula (const char *formula, const char *location)
virtual void queryComment (const char *comment)
virtual void queryEnd ()
Public Member Functions inherited from UTAP::StatementBuilder
StatementBuilder (TimedAutomataSystem *)
virtual void typeArrayOfSize (size_t)
Called to create an array type.
virtual void typeArrayOfType (size_t)
Called to create an array type.
virtual void typeStruct (PREFIX, uint32_t fields)
Used to construct a new struct type, which is then pushed onto the type stack.
virtual void structField (const char *name)
Used to declare the fields of a structure.
virtual void declTypeDef (const char *name)
A type definition.
virtual void declVar (const char *name, bool init)
Declare a new variable of the given name.
virtual void declInitialiserList (uint32_t num)
virtual void declFieldInit (const char *name)
virtual void declParameter (const char *name, bool)
virtual void declFuncBegin (const char *name)
virtual void declFuncEnd ()
virtual void blockBegin ()
virtual void blockEnd ()
virtual void emptyStatement ()
virtual void forBegin ()
virtual void forEnd ()
virtual void iterationBegin (const char *name)
virtual void iterationEnd (const char *name)
virtual void whileBegin ()
virtual void whileEnd ()
virtual void doWhileBegin ()
virtual void doWhileEnd ()
virtual void ifBegin ()
virtual void ifElse ()
virtual void ifEnd (bool)
virtual void exprStatement ()
virtual void returnStatement (bool)
virtual void assertStatement ()
virtual void exprCallBegin ()
Public Member Functions inherited from UTAP::ExpressionBuilder
ExpressionBuilder (TimedAutomataSystem *)
ExpressionFragments & getExpressions ()
virtual void addPosition (uint32_t position, uint32_t offset, uint32_t line, std::string path)
Add mapping from an absolute position to a relative XML element.
virtual void handleError (std::string)
virtual void handleWarning (std::string)
virtual void typeDuplicate ()
Duplicate type at the top of the type stack.
virtual void typePop ()
Pop type at the topof the type stack.
virtual void typeBool (PREFIX)
Called whenever a boolean type is parsed.
virtual void typeInt (PREFIX)
Called whenever an integer type is parsed.
virtual void typeDouble (PREFIX)
Called whenever a double type is parsed.
virtual void typeBoundedInt (PREFIX)
Called whenever an integer type with a range is parsed.
virtual void typeChannel (PREFIX)
Called whenever a channel type is parsed.
virtual void typeClock (PREFIX)
Called whenever a clock type is parsed.
virtual void typeVoid ()
Called whenever a void type is parsed.
virtual void typeScalar (PREFIX)
Called whenever a scalar type is parsed.
virtual void typeName (PREFIX, const char *name)
Called when a type name has been parsed.
virtual bool isType (const char *)
Must return true if and only if name is registered in the symbol table as a named type, for instance, "int" or "bool" or a user defined type.
virtual void exprTrue ()
virtual void exprFalse ()
virtual void exprDouble (double)
virtual void exprId (const char *varName)
virtual void exprNat (int32_t)
virtual void exprCallEnd (uint32_t n)
virtual void exprArray ()
virtual void exprPostIncrement ()
virtual void exprPreIncrement ()
virtual void exprPostDecrement ()
virtual void exprPreDecrement ()
virtual void exprAssignment (Constants::kind_t op)
virtual void exprUnary (Constants::kind_t unaryop)
virtual void exprBinary (Constants::kind_t binaryop)
virtual void exprNary (Constants::kind_t op, uint32_t num)
virtual void exprScenario (const char *name)
virtual expression_t exprScenario ()
virtual void exprTernary (Constants::kind_t ternaryop, bool firstMissing)
virtual void exprInlineIf ()
virtual void exprComma ()
virtual void exprDot (const char *)
virtual void exprDeadlock ()
virtual void exprForAllBegin (const char *name)
virtual void exprForAllEnd (const char *name)
virtual void exprExistsBegin (const char *name)
virtual void exprExistsEnd (const char *name)
virtual void exprSumBegin (const char *name)
virtual void exprSumEnd (const char *name)
virtual void exprSMCControl (int)
virtual void exprProbaQualitative (int, Constants::kind_t, Constants::kind_t, double)
virtual void exprProbaQuantitative (int, Constants::kind_t, bool stopCondition=false)
virtual void exprProbaCompare (int, Constants::kind_t, int, Constants::kind_t)
virtual void exprProbaExpected (int, const char *)
virtual void exprBuiltinFunction1 (Constants::kind_t)
virtual void exprBuiltinFunction2 (Constants::kind_t)
virtual void exprSimulate (int, int, int, bool=false, int=0)
virtual void exprMitlFormula ()
virtual void exprMitlUntil (int, int)
virtual void exprMitlRelease (int, int)
virtual void exprMitlDisj ()
virtual void exprMitlConj ()
virtual void exprMitlNext ()
virtual void exprMitlAtom ()
virtual void exprMitlDiamond (int, int)
virtual void exprMitlBox (int, int)
virtual void exprSpawn (int params)
virtual void exprExit ()
virtual void exprNumOf ()
virtual void exprForAllDynamicBegin (const char *, const char *)
virtual void exprForAllDynamicEnd (const char *name)
virtual void exprExistsDynamicBegin (const char *, const char *)
virtual void exprExistsDynamicEnd (const char *)
virtual void exprSumDynamicBegin (const char *, const char *)
virtual void exprSumDynamicEnd (const char *name)
virtual void exprForeachDynamicBegin (const char *, const char *)
virtual void exprForeachDynamicEnd (const char *name)
virtual void pushDynamicFrameOf (template_t *t, std::string name)
virtual void popDynamicFrameOf (std::string name)
Public Member Functions inherited from UTAP::AbstractBuilder
AbstractBuilder ()
virtual void setPosition (uint32_t, uint32_t)
Sets the current position.
virtual void breakStatement ()
virtual void continueStatement ()
virtual void switchBegin ()
virtual void switchEnd ()
virtual void caseBegin ()
virtual void caseEnd ()
virtual void defaultBegin ()
virtual void defaultEnd ()
virtual void exprProbaQuantitative (int, Constants::kind_t)
virtual void exprSimulate (int, int, int)
virtual void property ()
virtual void scenario (const char *)
virtual void parse (const char *)
virtual void exprDynamicProcessExpr (const char *)
virtual void exprMITLForAllDynamicBegin (const char *, const char *)
virtual void exprMITLForAllDynamicEnd (const char *name)
virtual void exprMITLExistsDynamicBegin (const char *, const char *)
virtual void exprMITLExistsDynamicEnd (const char *name)
Public Member Functions inherited from UTAP::ParserBuilder
virtual ~ParserBuilder ()
void handleWarning (const char *msg,...)
void handleError (const char *msg,...)
Protected Member Functions
declarations_t * getCurrentDeclarationBlock ()
virtual variable_t * addVariable (type_t type, const char *name, expression_t init)
virtual bool addFunction (type_t type, const char *name)
void addSelectSymbolToFrame (const char *name, frame_t &)
void declHybridRec (expression_t)
Protected Member Functions inherited from UTAP::ExpressionBuilder
void pushFrame (frame_t)
Push a new frame.
void popFrame ()
Pop the topmost frame.
bool resolve (std::string, symbol_t &)
expression_t makeConstant (int value)
expression_t makeConstant (double value)
type_t applyPrefix (PREFIX, type_t type)
Given a prefix and a type, this method creates a new type by applying the prefix.
virtual bool allowProcessReferences ()
If this method returns true, it is allowed to access the private identifiers of a process by prefixing the identifier with the process name.
Protected Attributes
int32_t currentProcPriority
The current process priority level.
edge_t * currentEdge
The edge under construction.
gantt_t * currentGantt
The gantt map under construction.
condition_t * currentCondition
The condition under construction.
update_t * currentUpdate
The update under construction.
message_t * currentMessage
The message under construction.
instanceLine_t * currentInstanceLine
The instance line under construction.
iodecl_t * currentIODecl
query_t * currentQuery
Protected Attributes inherited from UTAP::StatementBuilder
frame_t params
The params frame is used temporarily during parameter parsing.
function_t * currentFun
The function currently being parsed.
std::vector< BlockStatement * > blocks
Stack of nested statement blocks.
std::vector< type_t > fields
The types of a struct.
std::vector< std::string > labels
The labels of a struct.
Protected Attributes inherited from UTAP::ExpressionBuilder
ExpressionFragments fragments
Expression stack.
TypeFragments typeFragments
Type stack.
std::stack< frame_t > frames
Frame stack.
TimedAutomataSystem * system
Pointer to the system under construction.
template_t * currentTemplate
The template currently being parsed.
int32_t scalar_count
Counter for creating unique scalarset names.
std::map< std::string, frame_t > dynamicFrames
Protected Attributes inherited from UTAP::AbstractBuilder
position_t position
Additional Inherited Members
Public Types inherited from UTAP::ParserBuilder
enum PREFIX {
PREFIX_NONE = 0, PREFIX_CONST = 1, PREFIX_URGENT = 2, PREFIX_BROADCAST = 4,
PREFIX_URGENT_BROADCAST = 6, PREFIX_SYSTEM_META = 8, PREFIX_HYBRID = 16
}
Public Attributes inherited from UTAP::ParserBuilder
std::vector< std::string > lscTemplateNames
Static Protected Member Functions inherited from UTAP::StatementBuilder
static void collectDependencies (std::set< symbol_t > &, expression_t)
static void collectDependencies (std::set< symbol_t > &, type_t)
Detailed Description
This class constructs a TimedAutomataSystem.
It avoids as much type checking as possible - type checking should be done with the TypeChecker class. However some checks are more convenient to do in SystemBuilder:
states are not both committed and urgent
the source and target of an edge is a state
the dot operator is applied to a process or a structure (StatementBuilder)
functions are not recursive (StatementBuilder)
only declared functions are called (ExpressionBuilder)
functions are called with the correct number of arguments (StatementBuilder)
the initial state of a template is actually declared as a state
templates in instantiations have been declared
identifiers are not declared twice in the same scope (StatementBuilder)
type names do exist and are declared as types (StatementBuilder)
processes in the system line have been declared
Left hand side expressions are assigned the correct type by SystemBuilder; if not it would be difficult to represent dot-expressions.
SystemBuilder does not
check the correctness of variable initialisers, nor does it complete variable initialisers
type check expressions
check if arguments to functions or templates match the formal parameters
check if something is a proper left hand side value
check if things are assignment compatible
check conflicting use of synchronisations and guards on edge
handle properties
Use TypeChecker for these things.
Constructor & Destructor Documentation
SystemBuilder::SystemBuilder (TimedAutomataSystem * system)
References currentCondition, currentEdge, currentGantt, currentInstanceLine, currentIODecl, currentMessage, currentProcPriority, currentQuery, and currentUpdate.
Member Function Documentation
void SystemBuilder::addChanPriority (char separator) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addChanPriority(), UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::ExpressionFragments::pop(), and UTAP::ExpressionBuilder::system.
bool SystemBuilder::addFunction (type_t type, const char * name) protected virtual
Implements UTAP::StatementBuilder.
References UTAP::declarations_t::addFunction(), UTAP::StatementBuilder::currentFun, and getCurrentDeclarationBlock().
void SystemBuilder::addSelectSymbolToFrame (const char * name, frame_t & frame) protected
References UTAP::frame_t::addSymbol(), UTAP::Constants::CONSTANT, UTAP::type_t::createPrefix(), UTAP::ExpressionBuilder::handleError(), UTAP::ExpressionBuilder::handleWarning(), UTAP::type_t::is(), UTAP::type_t::isInteger(), UTAP::type_t::isScalar(), UTAP::ExpressionBuilder::TypeFragments::pop(), UTAP::Constants::RANGE, UTAP::ExpressionBuilder::resolve(), and UTAP::ExpressionBuilder::typeFragments.
Referenced by ganttDeclSelect(), ganttEntrySelect(), and procSelect().
variable_t * SystemBuilder::addVariable (type_t type, const char * name, expression_t init) protected virtual
Implements UTAP::StatementBuilder.
References UTAP::TimedAutomataSystem::addVariable(), UTAP::TimedAutomataSystem::addVariableToFunction(), UTAP::StatementBuilder::currentFun, UTAP::ExpressionBuilder::frames, getCurrentDeclarationBlock(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::afterUpdate () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::TimedAutomataSystem::setAfterUpdate(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::beforeUpdate () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::TimedAutomataSystem::setBeforeUpdate(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::beginChanPriority () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::beginChanPriority(), UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::ExpressionFragments::pop(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::declDynamicTemplate (std::string) virtual
Dynamic.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addDynamicTemplate(), UTAP::Constants::BROADCAST, UTAP::frame_t::createFrame(), UTAP::ExpressionBuilder::currentTemplate, UTAP::ExpressionBuilder::frames, UTAP::frame_t::getSize(), UTAP::ExpressionBuilder::handleError(), UTAP::StatementBuilder::params, UTAP::Constants::REF, and UTAP::ExpressionBuilder::system.
void UTAP::SystemBuilder::declHybridRec (expression_t) protected
void SystemBuilder::declIO (const char * name, int nbParam, int nbSync) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::iodecl_t::csp, currentIODecl, UTAP::ExpressionBuilder::fragments, UTAP::iodecl_t::inputs, UTAP::iodecl_t::instanceName, UTAP::iodecl_t::outputs, UTAP::iodecl_t::param, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::declProgress (bool hasGuard) virtual
Guard progress measure declaration.
Requires two expressions if hasGuard is true, otherwise one.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addProgressMeasure(), UTAP::ExpressionBuilder::fragments, getCurrentDeclarationBlock(), UTAP::ExpressionBuilder::ExpressionFragments::pop(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::defaultChanPriority () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::fragments, and UTAP::ExpressionBuilder::ExpressionFragments::push().
void SystemBuilder::done () virtual
Reimplemented from UTAP::AbstractBuilder.
void SystemBuilder::exprSync (Constants::synchronisation_t type) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addIODecl(), UTAP::iodecl_t::csp, currentIODecl, UTAP::ExpressionBuilder::fragments, UTAP::iodecl_t::inputs, UTAP::iodecl_t::outputs, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::Constants::SYNC_BANG, UTAP::Constants::SYNC_CSP, UTAP::Constants::SYNC_QUE, and UTAP::ExpressionBuilder::system.
void SystemBuilder::ganttDeclEnd () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addGantt(), currentGantt, UTAP::ExpressionBuilder::frames, getCurrentDeclarationBlock(), UTAP::gantt_t::parameters, UTAP::ExpressionBuilder::popFrame(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::ganttDeclSelect (const char * id) virtual
Reimplemented from UTAP::AbstractBuilder.
References addSelectSymbolToFrame(), and UTAP::ExpressionBuilder::frames.
void SystemBuilder::ganttDeclStart (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::frame_t::createFrame(), currentGantt, UTAP::ExpressionBuilder::frames, and UTAP::ExpressionBuilder::pushFrame().
void SystemBuilder::ganttEntryEnd () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentGantt, UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::frames, UTAP::ganttmap_t::mapping, UTAP::gantt_t::mapping, UTAP::ganttmap_t::parameters, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::ExpressionBuilder::popFrame(), and UTAP::ganttmap_t::predicate.
void SystemBuilder::ganttEntrySelect (const char * id) virtual
Reimplemented from UTAP::AbstractBuilder.
References addSelectSymbolToFrame(), and UTAP::ExpressionBuilder::frames.
void SystemBuilder::ganttEntryStart () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::frame_t::createFrame(), UTAP::ExpressionBuilder::frames, and UTAP::ExpressionBuilder::pushFrame().
declarations_t * SystemBuilder::getCurrentDeclarationBlock () protected
References UTAP::ExpressionBuilder::currentTemplate, UTAP::TimedAutomataSystem::getGlobals(), and UTAP::ExpressionBuilder::system.
Referenced by addFunction(), addVariable(), declProgress(), and ganttDeclEnd().
void SystemBuilder::hasPrechart (const bool pch) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::currentTemplate, and UTAP::template_t::hasPrechart.
void SystemBuilder::incProcPriority () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentProcPriority.
void SystemBuilder::instanceName (const char * name, bool templ = true) virtual
templ is true if the name of the instance contains parameters like "Train(1)".
Here, "Train" is the name of a template.
Otherwise the name of the instance can be for example "Train1", where "Train1" is a process that has been instantiated "Train1 = Train(1)". In this case, we cannot check that "Train1" exists yet, because the system declarations have not yet been parsed.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::frame_t::addSymbol(), UTAP::type_t::createPrimitive(), currentInstanceLine, UTAP::ExpressionBuilder::currentTemplate, UTAP::declarations_t::frame, UTAP::symbol_t::getData(), UTAP::type_t::getKind(), UTAP::frame_t::getSize(), UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::Constants::INSTANCE, UTAP::Constants::INSTANCELINE, UTAP::instance_t::parameters, UTAP::ExpressionBuilder::resolve(), and UTAP::instance_t::uid.
Referenced by instanceNameEnd().
void SystemBuilder::instanceNameBegin (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::frame_t::add(), UTAP::frame_t::createFrame(), UTAP::ExpressionBuilder::frames, UTAP::StatementBuilder::params, and UTAP::ExpressionBuilder::pushFrame().
void SystemBuilder::instanceNameEnd (const char * name, size_t arguments) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::instanceLine_t::addParameters(), UTAP::StatementBuilder::collectDependencies(), currentInstanceLine, UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::frames, UTAP::ExpressionBuilder::handleError(), UTAP::Constants::INSTANCE, instanceName(), UTAP::instance_t::parameters, UTAP::StatementBuilder::params, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::ExpressionBuilder::popFrame(), UTAP::ExpressionBuilder::resolve(), and UTAP::instance_t::restricted.
void SystemBuilder::instantiationBegin (const char * name, size_t parameters, const char * templ_name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::frame_t::add(), UTAP::frame_t::createFrame(), UTAP::ExpressionBuilder::frames, UTAP::ExpressionBuilder::handleError(), UTAP::Constants::INSTANCE, UTAP::Constants::LSCINSTANCE, UTAP::StatementBuilder::params, UTAP::ExpressionBuilder::pushFrame(), and UTAP::ExpressionBuilder::resolve().
void SystemBuilder::instantiationEnd (const char * name, size_t parameters, const char * templ_name, size_t arguments) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addInstance(), UTAP::TimedAutomataSystem::addLscInstance(), UTAP::StatementBuilder::collectDependencies(), UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::frames, UTAP::frame_t::getSize(), UTAP::ExpressionBuilder::handleError(), UTAP::Constants::INSTANCE, UTAP::Constants::LSCINSTANCE, UTAP::instance_t::parameters, UTAP::StatementBuilder::params, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::ExpressionBuilder::popFrame(), UTAP::ExpressionBuilder::resolve(), UTAP::instance_t::restricted, and UTAP::ExpressionBuilder::system.
void SystemBuilder::procBegin (const char * name, const bool isTA = true, const std::string type = "", const std::string mode = "") virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addTemplate(), UTAP::frame_t::createFrame(), UTAP::ExpressionBuilder::currentTemplate, UTAP::declarations_t::frame, UTAP::ExpressionBuilder::frames, UTAP::TimedAutomataSystem::getDynamicTemplate(), UTAP::frame_t::getSize(), UTAP::ExpressionBuilder::handleError(), UTAP::template_t::isDefined, UTAP::ParserBuilder::lscTemplateNames, UTAP::instance_t::parameters, UTAP::StatementBuilder::params, UTAP::ExpressionBuilder::pushFrame(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::procBranchpoint (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addBranchpoint(), and UTAP::ExpressionBuilder::currentTemplate.
virtual void UTAP::SystemBuilder::procCondition (const std::vector< char * > anchors, const int loc, const bool pch, const bool hot) virtual
Reimplemented from UTAP::AbstractBuilder.
void SystemBuilder::procCondition () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentCondition, UTAP::ExpressionBuilder::fragments, UTAP::condition_t::label, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::procEdgeBegin (const char * from, const char * to, const bool control, const char * actname) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addEdge(), UTAP::edge_t::assign, UTAP::frame_t::createFrame(), currentEdge, UTAP::ExpressionBuilder::currentTemplate, UTAP::ExpressionBuilder::frames, UTAP::symbol_t::getType(), UTAP::edge_t::guard, UTAP::ExpressionBuilder::handleError(), UTAP::type_t::isBranchpoint(), UTAP::type_t::isLocation(), UTAP::ExpressionBuilder::makeConstant(), UTAP::ExpressionBuilder::pushFrame(), UTAP::ExpressionBuilder::resolve(), and UTAP::edge_t::select.
void SystemBuilder::procEdgeEnd (const char * from = 0, const char * to = 0) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::popFrame().
void SystemBuilder::procEnd () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::currentTemplate, and UTAP::ExpressionBuilder::popFrame().
void SystemBuilder::process (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addProcess(), UTAP::symbol_t::getData(), UTAP::type_t::getKind(), UTAP::symbol_t::getName(), UTAP::symbol_t::getType(), UTAP::Constants::INSTANCE, procPriority(), UTAP::ExpressionBuilder::resolve(), UTAP::type_t::size(), UTAP::symbol(), and UTAP::ExpressionBuilder::system.
void SystemBuilder::processListEnd () virtual
Reimplemented from UTAP::AbstractBuilder.
void SystemBuilder::procGuard () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentEdge, UTAP::ExpressionBuilder::fragments, UTAP::edge_t::guard, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::procInstanceLine () virtual
Adds an instance line to the current template.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addInstanceLine(), currentInstanceLine, and UTAP::ExpressionBuilder::currentTemplate.
void SystemBuilder::procLscUpdate (const char * anchor, const int loc, const bool pch) virtual
Add an update to the current template.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addUpdate(), UTAP::ExpressionBuilder::currentTemplate, currentUpdate, UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::type_t::isInstanceLine(), UTAP::update_t::label, UTAP::ExpressionBuilder::makeConstant(), and UTAP::ExpressionBuilder::resolve().
void SystemBuilder::procLscUpdate () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentUpdate, UTAP::ExpressionBuilder::fragments, UTAP::update_t::label, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::procMessage (const char * from, const char * to, const int loc, const bool pch) virtual
Add a message to the current template.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addMessage(), currentMessage, UTAP::ExpressionBuilder::currentTemplate, UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::type_t::isInstanceLine(), and UTAP::ExpressionBuilder::resolve().
void SystemBuilder::procMessage (Constants::synchronisation_t type) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::expression_t::createSync(), currentMessage, UTAP::ExpressionBuilder::fragments, UTAP::message_t::label, UTAP::ExpressionBuilder::ExpressionFragments::pop(), and UTAP::AbstractBuilder::position.
void SystemBuilder::procPriority (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References currentProcPriority, UTAP::ExpressionBuilder::handleError(), UTAP::ExpressionBuilder::resolve(), UTAP::TimedAutomataSystem::setProcPriority(), UTAP::symbol(), and UTAP::ExpressionBuilder::system.
Referenced by process().
void SystemBuilder::procProb () virtual
Reimplemented from UTAP::AbstractBuilder.
References currentEdge, UTAP::ExpressionBuilder::fragments, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::procSelect (const char * id) virtual
Reimplemented from UTAP::AbstractBuilder.
References addSelectSymbolToFrame(), currentEdge, and UTAP::edge_t::select.
void SystemBuilder::procState (const char * name, bool hasInvariant, bool hasER) virtual
Add a state to the current template.
An invariant expression is expected on and popped from the expression stack if hasInvariant is true.
Reimplemented from UTAP::AbstractBuilder.
References UTAP::template_t::addLocation(), UTAP::ExpressionBuilder::currentTemplate, UTAP::ExpressionBuilder::fragments, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::procStateCommit (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References COMMITTED, UTAP::type_t::createPrefix(), UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::type_t::is(), UTAP::type_t::isLocation(), UTAP::AbstractBuilder::position, UTAP::ExpressionBuilder::resolve(), UTAP::symbol_t::setType(), and URGENT.
void SystemBuilder::procStateInit (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::ExpressionBuilder::currentTemplate, UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::template_t::init, UTAP::type_t::isLocation(), and UTAP::ExpressionBuilder::resolve().
void SystemBuilder::procStateUrgent (const char * name) virtual
Reimplemented from UTAP::AbstractBuilder.
References COMMITTED, UTAP::type_t::createPrefix(), UTAP::symbol_t::getType(), UTAP::ExpressionBuilder::handleError(), UTAP::type_t::is(), UTAP::type_t::isLocation(), UTAP::AbstractBuilder::position, UTAP::ExpressionBuilder::resolve(), UTAP::symbol_t::setType(), and URGENT.
void SystemBuilder::procSync (Constants::synchronisation_t type) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::expression_t::createSync(), currentEdge, UTAP::ExpressionBuilder::fragments, UTAP::ExpressionBuilder::ExpressionFragments::pop(), UTAP::AbstractBuilder::position, and UTAP::edge_t::sync.
void SystemBuilder::procUpdate () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::edge_t::assign, currentEdge, UTAP::ExpressionBuilder::fragments, and UTAP::ExpressionBuilder::ExpressionFragments::pop().
void SystemBuilder::queryBegin () virtual
Verification queries.
Reimplemented from UTAP::AbstractBuilder.
References currentQuery.
void SystemBuilder::queryComment (const char * comment) virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::query_t::comment, comment, and currentQuery.
void SystemBuilder::queryEnd () virtual
Reimplemented from UTAP::AbstractBuilder.
References UTAP::TimedAutomataSystem::addQuery(), currentQuery, and UTAP::ExpressionBuilder::system.
void SystemBuilder::queryFormula (const char * formula, const char * location) virtual
Reimplemented from UTAP::AbstractBuilder.
References currentQuery, UTAP::query_t::formula, and UTAP::query_t::location.
Member Data Documentation
condition_t* UTAP::SystemBuilder::currentCondition protected
The condition under construction.
Referenced by procCondition(), and SystemBuilder().
edge_t* UTAP::SystemBuilder::currentEdge protected
The edge under construction.
Referenced by procEdgeBegin(), procGuard(), procProb(), procSelect(), procSync(), procUpdate(), and SystemBuilder().
gantt_t* UTAP::SystemBuilder::currentGantt protected
The gantt map under construction.
Referenced by ganttDeclEnd(), ganttDeclStart(), ganttEntryEnd(), and SystemBuilder().
instanceLine_t* UTAP::SystemBuilder::currentInstanceLine protected
The instance line under construction.
Referenced by instanceName(), instanceNameEnd(), procInstanceLine(), and SystemBuilder().
iodecl_t* UTAP::SystemBuilder::currentIODecl protected
Referenced by declIO(), exprSync(), and SystemBuilder().
message_t* UTAP::SystemBuilder::currentMessage protected
The message under construction.
Referenced by procMessage(), and SystemBuilder().
int32_t UTAP::SystemBuilder::currentProcPriority protected
The current process priority level.
Referenced by incProcPriority(), procPriority(), and SystemBuilder().
query_t* UTAP::SystemBuilder::currentQuery protected
Referenced by queryBegin(), queryComment(), queryEnd(), queryFormula(), and SystemBuilder().
update_t* UTAP::SystemBuilder::currentUpdate protected
The update under construction.
Referenced by procLscUpdate(), and SystemBuilder().
The documentation for this class was generated from the following files:
systembuilder.h
systembuilder.cpp