libutap: UTAP::BlockStatement Class Reference
UTAP::BlockStatement Class Reference
#include <statement.h>
Public Types
typedef std::vector< Statement * >
::const_iterator const_iterator
typedef std::vector< Statement * >
::iterator iterator
Public Member Functions
BlockStatement (frame_t)
virtual ~BlockStatement ()
virtual int32_t accept (StatementVisitor *visitor)
virtual bool returns ()
frame_t getFrame ()
void push_stat (Statement *stat)
Statement * pop_stat ()
Statement * back ()
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
std::string toString (std::string prefix) const
Public Member Functions inherited from UTAP::Statement
virtual ~Statement ()
Public Member Functions inherited from UTAP::declarations_t
bool addFunction (type_t type, std::string, function_t *&)
Add function declaration.
std::string toString (bool global=false) const
The following methods are used to write the declarations in an XML file.
std::string getConstants () const
std::string getTypeDefinitions () const
std::string getVariables (bool global) const
std::string getFunctions () const
Protected Attributes
std::vector< Statement * > stats
frame_t frame
Additional Inherited Members
Public Attributes inherited from UTAP::declarations_t
frame_t frame
std::list< variable_t > variables
Variables.
std::list< function_t > functions
Functions.
std::list< progress_t > progress
Progress measures.
std::list< iodecl_t > iodecl
std::list< gantt_t > ganttChart
Protected Member Functions inherited from UTAP::Statement
Statement ()
Member Typedef Documentation
typedef std::vector<Statement *>::const_iterator UTAP::BlockStatement::const_iterator
typedef std::vector<Statement *>::iterator UTAP::BlockStatement::iterator
Constructor & Destructor Documentation
BlockStatement::BlockStatement (frame_t frame)
References frame.
BlockStatement::~BlockStatement () virtual
References pop_stat(), and stats.
Member Function Documentation
int32_t BlockStatement::accept (StatementVisitor * visitor) virtual
Implements UTAP::Statement.
Reimplemented in UTAP::DefaultStatement, UTAP::CaseStatement, and UTAP::SwitchStatement.
References UTAP::StatementVisitor::visitBlockStatement().
Referenced by UTAP::SignalFlow::visitExpression(), and UTAP::TypeChecker::visitFunction().
Statement * BlockStatement::back ()
References stats.
Referenced by pop_stat(), and returns().
BlockStatement::const_iterator BlockStatement::begin () const
References stats.
Referenced by returns(), UTAP::TypeChecker::visitBlockStatement(), UTAP::SignalFlow::visitBlockStatement(), UTAP::AbstractStatementVisitor::visitBlockStatement(), and UTAP::ExpressionVisitor::visitBlockStatement().
BlockStatement::iterator BlockStatement::begin ()
References stats.
BlockStatement::const_iterator BlockStatement::end () const
References stats.
Referenced by returns(), UTAP::TypeChecker::visitBlockStatement(), UTAP::SignalFlow::visitBlockStatement(), UTAP::AbstractStatementVisitor::visitBlockStatement(), and UTAP::ExpressionVisitor::visitBlockStatement().
BlockStatement::iterator BlockStatement::end ()
References stats.
frame_t UTAP::BlockStatement::getFrame () inline
References frame.
Referenced by UTAP::TypeChecker::visitBlockStatement(), UTAP::ExpressionVisitor::visitBlockStatement(), UTAP::SignalFlow::visitExpression(), and UTAP::TypeChecker::visitFunction().
Statement * BlockStatement::pop_stat ()
References back(), and stats.
Referenced by ~BlockStatement().
void BlockStatement::push_stat (Statement * stat)
References stats.
bool BlockStatement::returns () virtual
Implements UTAP::Statement.
Reimplemented in UTAP::DefaultStatement, UTAP::CaseStatement, and UTAP::SwitchStatement.
References back(), begin(), end(), and UTAP::Statement::returns().
std::string BlockStatement::toString (std::string prefix) const virtual
Implements UTAP::Statement.
Reimplemented in UTAP::CaseStatement, and UTAP::SwitchStatement.
References stats.
Referenced by UTAP::SwitchStatement::toString(), and UTAP::CaseStatement::toString().
Member Data Documentation
frame_t UTAP::BlockStatement::frame protected
Referenced by BlockStatement(), and getFrame().
std::vector<Statement*> UTAP::BlockStatement::stats protected
Referenced by back(), begin(), end(), pop_stat(), push_stat(), toString(), and ~BlockStatement().
The documentation for this class was generated from the following files:
statement.h
statement.cpp