libutap: UTAP::ParserBuilder Class Reference
UTAP::ParserBuilder Class Reference abstract
The ParserBuilder interface is used by the parser to output the parsed system.
#include <builder.h>
Public Types
enum PREFIX {
PREFIX_NONE = 0, PREFIX_CONST = 1, PREFIX_URGENT = 2, PREFIX_BROADCAST = 4,
PREFIX_URGENT_BROADCAST = 6, PREFIX_SYSTEM_META = 8, PREFIX_HYBRID = 16
}
Public Member Functions
virtual ~ParserBuilder ()
virtual void addPosition (uint32_t position, uint32_t offset, uint32_t line, std::string path)=0
Add mapping from an absolute position to a relative XML element.
virtual void setPosition (uint32_t a, uint32_t b)=0
Sets the current position.
virtual void handleError (std::string)=0
virtual void handleWarning (std::string)=0
void handleWarning (const char *msg,...)
void handleError (const char *msg,...)
virtual bool isType (const char *)=0
Must return true if and only if name is registered in the symbol table as a named type, for instance, "int" or "bool" or a user defined type.
virtual void typeDuplicate ()=0
Duplicate type at the top of the type stack.
virtual void typePop ()=0
Pop type at the topof the type stack.
virtual void typeBool (PREFIX)=0
Called whenever a boolean type is parsed.
virtual void typeInt (PREFIX)=0
Called whenever an integer type is parsed.
virtual void typeDouble (PREFIX)=0
Called whenever a double type is parsed.
virtual void typeBoundedInt (PREFIX)=0
Called whenever an integer type with a range is parsed.
virtual void typeChannel (PREFIX)=0
Called whenever a channel type is parsed.
virtual void typeClock (PREFIX)=0
Called whenever a clock type is parsed.
virtual void typeVoid ()=0
Called whenever a void type is parsed.
virtual void typeArrayOfSize (size_t)=0
Called to create an array type.
virtual void typeArrayOfType (size_t)=0
Called to create an array type.
virtual void typeScalar (PREFIX)=0
Called whenever a scalar type is parsed.
virtual void typeName (PREFIX, const char *name)=0
Called when a type name has been parsed.
virtual void typeStruct (PREFIX, uint32_t fields)=0
Called when a struct-type has been parsed.
virtual void structField (const char *name)=0
Called to declare a field of a structure.
virtual void declTypeDef (const char *name)=0
Used when a typedef declaration was parsed.
virtual void declVar (const char *name, bool init)=0
Called to when a variable declaration has been parsed.
virtual void declInitialiserList (uint32_t num)=0
virtual void declFieldInit (const char *name)=0
virtual void declProgress (bool hasGuard)=0
Guard progress measure declaration.
virtual void ganttDeclStart (const char *name)=0
virtual void ganttDeclSelect (const char *id)=0
virtual void ganttDeclEnd ()=0
virtual void ganttEntryStart ()=0
virtual void ganttEntrySelect (const char *id)=0
virtual void ganttEntryEnd ()=0
virtual void declParameter (const char *name, bool ref)=0
virtual void declFuncBegin (const char *name)=0
virtual void declFuncEnd ()=0
virtual void procBegin (const char *name, const bool isTA=true, const std::string type="", const std::string mode="")=0
virtual void procEnd ()=0
virtual void procState (const char *name, bool hasInvariant, bool hasER)=0
virtual void procStateCommit (const char *name)=0
virtual void procStateUrgent (const char *name)=0
virtual void procStateInit (const char *name)=0
virtual void procEdgeBegin (const char *from, const char *to, const bool control, const char *actname="")=0
virtual void procEdgeEnd (const char *from, const char *to)=0
virtual void procSelect (const char *id)=0
virtual void procGuard ()=0
virtual void procSync (Constants::synchronisation_t type)=0
virtual void procUpdate ()=0
virtual void procProb ()=0
virtual void procBranchpoint (const char *name)=0
virtual void procInstanceLine ()=0
virtual void instanceName (const char *name, bool templ=true)=0
virtual void instanceNameBegin (const char *name)=0
virtual void instanceNameEnd (const char *name, size_t arguments)=0
virtual void procMessage (const char *from, const char *to, const int loc, const bool pch)=0
virtual void procMessage (Constants::synchronisation_t type)=0
virtual void procCondition (const std::vector< char * > anchors, const int loc, const bool pch, const bool hot)=0
virtual void procCondition ()=0
virtual void procLscUpdate (const char *anchor, const int loc, const bool pch)=0
virtual void procLscUpdate ()=0
virtual void hasPrechart (const bool pch)=0
virtual void blockBegin ()=0
virtual void blockEnd ()=0
virtual void emptyStatement ()=0
virtual void forBegin ()=0
virtual void forEnd ()=0
virtual void iterationBegin (const char *name)=0
virtual void iterationEnd (const char *name)=0
virtual void whileBegin ()=0
virtual void whileEnd ()=0
virtual void doWhileBegin ()=0
virtual void doWhileEnd ()=0
virtual void ifBegin ()=0
virtual void ifElse ()=0
virtual void ifEnd (bool)=0
virtual void breakStatement ()=0
virtual void continueStatement ()=0
virtual void switchBegin ()=0
virtual void switchEnd ()=0
virtual void caseBegin ()=0
virtual void caseEnd ()=0
virtual void defaultBegin ()=0
virtual void defaultEnd ()=0
virtual void exprStatement ()=0
virtual void returnStatement (bool)=0
virtual void assertStatement ()=0
virtual void exprFalse ()=0
virtual void exprTrue ()=0
virtual void exprDouble (double)=0
virtual void exprId (const char *varName)=0
virtual void exprNat (int32_t)=0
virtual void exprCallBegin ()=0
virtual void exprCallEnd (uint32_t n)=0
virtual void exprArray ()=0
virtual void exprPostIncrement ()=0
virtual void exprPreIncrement ()=0
virtual void exprPostDecrement ()=0
virtual void exprPreDecrement ()=0
virtual void exprAssignment (Constants::kind_t op)=0
virtual void exprUnary (Constants::kind_t unaryop)=0
virtual void exprBinary (Constants::kind_t binaryop)=0
virtual void exprNary (Constants::kind_t, uint32_t num)=0
virtual void exprScenario (const char *name)=0
virtual void exprTernary (Constants::kind_t ternaryop, bool firstMissing=false)=0
virtual void exprInlineIf ()=0
virtual void exprComma ()=0
virtual void exprDot (const char *)=0
virtual void exprDeadlock ()=0
virtual void exprForAllBegin (const char *name)=0
virtual void exprForAllEnd (const char *name)=0
virtual void exprExistsBegin (const char *name)=0
virtual void exprExistsEnd (const char *name)=0
virtual void exprSumBegin (const char *name)=0
virtual void exprSumEnd (const char *name)=0
virtual void exprSync (Constants::synchronisation_t type)=0
virtual void declIO (const char *, int, int)=0
virtual void exprSMCControl (int)=0
virtual void exprProbaQualitative (int, Constants::kind_t, Constants::kind_t, double)=0
virtual void exprProbaQuantitative (int, Constants::kind_t, bool=false)=0
virtual void exprProbaCompare (int, Constants::kind_t, int, Constants::kind_t)=0
virtual void exprProbaExpected (int, const char *)=0
virtual void exprBuiltinFunction1 (Constants::kind_t)=0
virtual void exprBuiltinFunction2 (Constants::kind_t)=0
virtual void exprMitlFormula ()=0
virtual void exprMitlUntil (int, int)=0
virtual void exprMitlRelease (int, int)=0
virtual void exprMitlDisj ()=0
virtual void exprMitlConj ()=0
virtual void exprMitlNext ()=0
virtual void exprMitlAtom ()=0
virtual void exprMitlDiamond (int, int)=0
virtual void exprMitlBox (int, int)=0
virtual void exprSimulate (int, int, int, bool=false, int=0)=0
virtual void instantiationBegin (const char *id, size_t parameters, const char *templ)=0
virtual void instantiationEnd (const char *id, size_t parameters, const char *templ, size_t arguments)=0
virtual void process (const char *)=0
virtual void processListEnd ()=0
virtual void done ()=0
virtual void property ()=0
virtual void scenario (const char *)=0
virtual void parse (const char *)=0
virtual void beforeUpdate ()=0
virtual void afterUpdate ()=0
virtual void beginChanPriority ()=0
virtual void addChanPriority (char separator)=0
virtual void defaultChanPriority ()=0
virtual void incProcPriority ()=0
virtual void procPriority (const char *)=0
virtual void declDynamicTemplate (std::string)=0
Dynamic.
virtual void exprSpawn (int)=0
virtual void exprExit ()=0
virtual void exprNumOf ()=0
virtual void exprForAllDynamicBegin (const char *, const char *)=0
virtual void exprForAllDynamicEnd (const char *name)=0
virtual void exprExistsDynamicBegin (const char *, const char *)=0
virtual void exprExistsDynamicEnd (const char *name)=0
virtual void exprSumDynamicBegin (const char *, const char *)=0
virtual void exprSumDynamicEnd (const char *name)=0
virtual void exprForeachDynamicBegin (const char *, const char *)=0
virtual void exprForeachDynamicEnd (const char *name)=0
virtual void exprMITLForAllDynamicBegin (const char *, const char *)=0
virtual void exprMITLForAllDynamicEnd (const char *name)=0
virtual void exprMITLExistsDynamicBegin (const char *, const char *)=0
virtual void exprMITLExistsDynamicEnd (const char *name)=0
virtual void exprDynamicProcessExpr (const char *)=0
virtual void queryBegin ()=0
Verification queries.
virtual void queryFormula (const char *formula, const char *location)=0
virtual void queryComment (const char *comment)=0
virtual void queryEnd ()=0
Public Attributes
std::vector< std::string > lscTemplateNames
Detailed Description
The ParserBuilder interface is used by the parser to output the parsed system.
The parser itself will only parse the system - it will not actually store or otherwise process the input. Instead, the parser is configured with an implementation of the ParserBuilder interface. Productions in the BNF implemented by the parser correspond to methods in the ParserBuilder interface.
Errors (such as type errors) can be reported back to the parser by either throwing a TypeException or by calling an error method in the ErrorHandler that has been set by a call to setErrorHandler().
Expressions
Expressions are reported in reverse polish notation using the exprXXX methods.
Declarations
The proper protocol for declaring a new type name is to
report the type using the typeXXX methods
call declTypeDef(name) to declare the type-name
The proper protocol for declaring a variable is to
report the type using the typeXXX methods
optionally report an expression for the initialiser
call declVar(name, init), where init is true if and only if an initialiser has been reported
Member Enumeration Documentation
enum UTAP::ParserBuilder::PREFIX
Enumerator
PREFIX_NONE
PREFIX_CONST
PREFIX_URGENT
PREFIX_BROADCAST
PREFIX_URGENT_BROADCAST
PREFIX_SYSTEM_META
PREFIX_HYBRID
Constructor & Destructor Documentation
virtual UTAP::ParserBuilder::~ParserBuilder () inline virtual
Member Function Documentation
virtual void UTAP::ParserBuilder::addChanPriority (char separator) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::addPosition (uint32_t position, uint32_t offset, uint32_t line, std::string path) pure virtual
Add mapping from an absolute position to a relative XML element.
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
Referenced by UTAP::PositionTracker::newline(), and UTAP::PositionTracker::setPath().
virtual void UTAP::ParserBuilder::afterUpdate () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::assertStatement () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::beforeUpdate () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::beginChanPriority () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::blockBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::blockEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::breakStatement () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::caseBegin () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::caseEnd () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::continueStatement () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::declDynamicTemplate (std::string) pure virtual
Dynamic.
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::declFieldInit (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declFuncBegin (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declFuncEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declInitialiserList (uint32_t num) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declIO (const char * , int , int) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::declParameter (const char * name, bool ref) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declProgress (bool hasGuard) pure virtual
Guard progress measure declaration.
Requires two expressions if hasGuard is true, otherwise one.
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::declTypeDef (const char * name) pure virtual
Used when a typedef declaration was parsed.
name is the name of the new type.
Implemented in UTAP::PrettyPrinter, UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::declVar (const char * name, bool init) pure virtual
Called to when a variable declaration has been parsed.
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::defaultBegin () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::defaultChanPriority () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::defaultEnd () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::done () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::doWhileBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::doWhileEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::emptyStatement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::exprArray () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprAssignment (Constants::kind_t op) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprBinary (Constants::kind_t binaryop) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprBuiltinFunction1 (Constants::kind_t) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprBuiltinFunction2 (Constants::kind_t) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprCallBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::exprCallEnd (uint32_t n) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprComma () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprDeadlock () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprDot (const char *) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprDouble (double) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprDynamicProcessExpr (const char *) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::exprExistsBegin (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprExistsDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprExistsDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprExistsEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprExit () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprFalse () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprForAllBegin (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprForAllDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprForAllDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprForAllEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprForeachDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprForeachDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprId (const char * varName) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprInlineIf () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprMitlAtom () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMitlBox (int , int) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprMitlConj () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMitlDiamond (int , int) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprMitlDisj () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMITLExistsDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::exprMITLExistsDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::exprMITLForAllDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::exprMITLForAllDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::exprMitlFormula () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMitlNext () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMitlRelease (int , int) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprMitlUntil (int , int) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprNary (Constants::kind_t , uint32_t num) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprNat (int32_t) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprNumOf () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprPostDecrement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprPostIncrement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprPreDecrement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprPreIncrement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprProbaCompare (int , Constants::kind_t , int , Constants::kind_t) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprProbaExpected (int , const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprProbaQualitative (int , Constants::kind_t , Constants::kind_t , double) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprProbaQuantitative (int , Constants::kind_t , bool = false) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprScenario (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprSimulate (int , int , int , bool = false, int = 0) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprSMCControl (int) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprSpawn (int) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprStatement () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::exprSumBegin (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprSumDynamicBegin (const char * , const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprSumDynamicEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprSumEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprSync (Constants::synchronisation_t type) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::exprTernary (Constants::kind_t ternaryop, bool firstMissing = false) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::ExpressionBuilder.
virtual void UTAP::ParserBuilder::exprTrue () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::exprUnary (Constants::kind_t unaryop) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::forBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::forEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::ganttDeclEnd () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ganttDeclSelect (const char * id) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ganttDeclStart (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ganttEntryEnd () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ganttEntrySelect (const char * id) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ganttEntryStart () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::handleError (std::string) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
Referenced by UTAP::ExpressionBuilder::exprDot(), handleError(), and utap_error().
void ParserBuilder::handleError (const char * msg, ...)
References handleError().
virtual void UTAP::ParserBuilder::handleWarning (std::string) pure virtual
Implemented in UTAP::ExpressionBuilder, and UTAP::PrettyPrinter.
Referenced by handleWarning().
void ParserBuilder::handleWarning (const char * msg, ...)
References handleWarning().
virtual void UTAP::ParserBuilder::hasPrechart (const bool pch) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::ifBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::ifElse () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::ifEnd (bool) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::incProcPriority () pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::instanceName (const char * name, bool templ = true) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::instanceNameBegin (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::instanceNameEnd (const char * name, size_t arguments) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::instantiationBegin (const char * id, size_t parameters, const char * templ) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::instantiationEnd (const char * id, size_t parameters, const char * templ, size_t arguments) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual bool UTAP::ParserBuilder::isType (const char *) pure virtual
Must return true if and only if name is registered in the symbol table as a named type, for instance, "int" or "bool" or a user defined type.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::iterationBegin (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::iterationEnd (const char * name) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::parse (const char *) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procBegin (const char * name, const bool isTA = true, const std::string type = "", const std::string mode = "") pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procBranchpoint (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procCondition (const std::vector< char * > anchors, const int loc, const bool pch, const bool hot) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procCondition () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procEdgeBegin (const char * from, const char * to, const bool control, const char * actname = "") pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procEdgeEnd (const char * from, const char * to) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procEnd () pure virtual
Implemented in UTAP::SystemBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::process (const char *) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::processListEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::procGuard () pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procInstanceLine () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procLscUpdate (const char * anchor, const int loc, const bool pch) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procLscUpdate () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procMessage (const char * from, const char * to, const int loc, const bool pch) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procMessage (Constants::synchronisation_t type) pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procPriority (const char *) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::procProb () pure virtual
Implemented in UTAP::SystemBuilder, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::procSelect (const char * id) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procState (const char * name, bool hasInvariant, bool hasER) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procStateCommit (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procStateInit (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procStateUrgent (const char * name) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procSync (Constants::synchronisation_t type) pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::procUpdate () pure virtual
Implemented in UTAP::SystemBuilder, UTAP::AbstractBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::property () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::queryBegin () pure virtual
Verification queries.
Implemented in UTAP::AbstractBuilder, UTAP::SystemBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::queryComment (const char * comment) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::SystemBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::queryEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::SystemBuilder, and UTAP::PrettyPrinter.
virtual void UTAP::ParserBuilder::queryFormula (const char * formula, const char * location) pure virtual
Implemented in UTAP::AbstractBuilder, and UTAP::SystemBuilder.
virtual void UTAP::ParserBuilder::returnStatement (bool) pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::scenario (const char *) pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::setPosition (uint32_t a, uint32_t b) pure virtual
Sets the current position.
The current position indicates where in the input file the current productions can be found.
Implemented in UTAP::AbstractBuilder.
Referenced by UTAP::PositionTracker::increment(), and utap_error().
virtual void UTAP::ParserBuilder::structField (const char * name) pure virtual
Called to declare a field of a structure.
The type of the field has been reported using a typeXXX method prior to the call of structField(). In case of array fields, 'dim' expressions indicating the array sizes have been reported.
Implemented in UTAP::PrettyPrinter, UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::switchBegin () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::switchEnd () pure virtual
Implemented in UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeArrayOfSize (size_t) pure virtual
Called to create an array type.
The size of the array was previously pushed as an expression.
Implemented in UTAP::PrettyPrinter, UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::typeArrayOfType (size_t) pure virtual
Called to create an array type.
The size of the array was previously pushed as a type.
Implemented in UTAP::PrettyPrinter, UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::typeBool (PREFIX) pure virtual
Called whenever a boolean type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeBoundedInt (PREFIX) pure virtual
Called whenever an integer type with a range is parsed.
Expressions for the lower and upper have been pushed before.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeChannel (PREFIX) pure virtual
Called whenever a channel type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeClock (PREFIX) pure virtual
Called whenever a clock type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeDouble (PREFIX) pure virtual
Called whenever a double type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeDuplicate () pure virtual
Duplicate type at the top of the type stack.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeInt (PREFIX) pure virtual
Called whenever an integer type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeName (PREFIX , const char * name) pure virtual
Called when a type name has been parsed.
Prefix indicates whether the type named was prefixed (e.g. with 'const').
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typePop () pure virtual
Pop type at the topof the type stack.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeScalar (PREFIX) pure virtual
Called whenever a scalar type is parsed.
The size of the scalar set was pushed as an expression before.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::typeStruct (PREFIX , uint32_t fields) pure virtual
Called when a struct-type has been parsed.
Prior to the call 'fields' fields must have been declared using the structXXX methods.
Implemented in UTAP::PrettyPrinter, UTAP::AbstractBuilder, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::typeVoid () pure virtual
Called whenever a void type is parsed.
Implemented in UTAP::ExpressionBuilder, UTAP::PrettyPrinter, and UTAP::AbstractBuilder.
virtual void UTAP::ParserBuilder::whileBegin () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
virtual void UTAP::ParserBuilder::whileEnd () pure virtual
Implemented in UTAP::AbstractBuilder, UTAP::PrettyPrinter, and UTAP::StatementBuilder.
Member Data Documentation
std::vector<std::string> UTAP::ParserBuilder::lscTemplateNames
Referenced by UTAP::SystemBuilder::procBegin().
The documentation for this class was generated from the following files:
builder.h
abstractbuilder.cpp