libutap: UTAP::ExpressionBuilder::TypeFragments Class Reference
UTAP::ExpressionBuilder::TypeFragments Class Reference
#include <expressionbuilder.h>
Public Member Functions
type_t & operator[] (int idx)
void push (type_t value)
void pop ()
void duplicate ()
Member Function Documentation
void UTAP::ExpressionBuilder::TypeFragments::duplicate () inline
Referenced by UTAP::ExpressionBuilder::typeDuplicate().
type_t& UTAP::ExpressionBuilder::TypeFragments::operator[] (int idx) inline
void UTAP::ExpressionBuilder::TypeFragments::pop () inline
Referenced by UTAP::SystemBuilder::addSelectSymbolToFrame(), UTAP::StatementBuilder::declFuncBegin(), UTAP::StatementBuilder::declParameter(), UTAP::StatementBuilder::declTypeDef(), UTAP::StatementBuilder::declVar(), UTAP::ExpressionBuilder::exprForAllBegin(), UTAP::StatementBuilder::iterationBegin(), UTAP::StatementBuilder::structField(), UTAP::StatementBuilder::typeArrayOfType(), and UTAP::ExpressionBuilder::typePop().
void UTAP::ExpressionBuilder::TypeFragments::push (type_t value) inline
Referenced by UTAP::ExpressionBuilder::typeBool(), UTAP::ExpressionBuilder::typeBoundedInt(), UTAP::ExpressionBuilder::typeChannel(), UTAP::ExpressionBuilder::typeClock(), UTAP::ExpressionBuilder::typeDouble(), UTAP::ExpressionBuilder::typeInt(), UTAP::ExpressionBuilder::typeName(), UTAP::ExpressionBuilder::typeScalar(), UTAP::StatementBuilder::typeStruct(), and UTAP::ExpressionBuilder::typeVoid().
The documentation for this class was generated from the following file:
expressionbuilder.h