libutap: UTAP::ExpressionBuilder::ExpressionFragments Class Reference
UTAP::ExpressionBuilder::ExpressionFragments Class Reference
#include <expressionbuilder.h>
Public Member Functions
expression_t & operator[] (int idx)
void push (expression_t e)
void pop ()
void pop (uint32_t n)
uint32_t size ()
Member Function Documentation
expression_t& UTAP::ExpressionBuilder::ExpressionFragments::operator[] (int idx) inline
void UTAP::ExpressionBuilder::ExpressionFragments::pop () inline
Referenced by UTAP::SystemBuilder::addChanPriority(), UTAP::SystemBuilder::afterUpdate(), UTAP::StatementBuilder::assertStatement(), UTAP::SystemBuilder::beforeUpdate(), UTAP::SystemBuilder::beginChanPriority(), UTAP::StatementBuilder::declInitialiserList(), UTAP::SystemBuilder::declIO(), UTAP::SystemBuilder::declProgress(), UTAP::StatementBuilder::declVar(), UTAP::StatementBuilder::doWhileEnd(), UTAP::ExpressionBuilder::exprArray(), UTAP::ExpressionBuilder::exprAssignment(), UTAP::ExpressionBuilder::exprBinary(), UTAP::ExpressionBuilder::exprBuiltinFunction2(), UTAP::ExpressionBuilder::exprCallEnd(), UTAP::ExpressionBuilder::exprComma(), UTAP::ExpressionBuilder::exprExistsDynamicEnd(), UTAP::ExpressionBuilder::exprForAllDynamicEnd(), UTAP::ExpressionBuilder::exprForeachDynamicEnd(), UTAP::ExpressionBuilder::exprInlineIf(), UTAP::ExpressionBuilder::exprMitlAtom(), UTAP::ExpressionBuilder::exprMitlBox(), UTAP::ExpressionBuilder::exprMitlConj(), UTAP::ExpressionBuilder::exprMitlDiamond(), UTAP::ExpressionBuilder::exprMitlDisj(), UTAP::ExpressionBuilder::exprMitlFormula(), UTAP::ExpressionBuilder::exprMitlNext(), UTAP::ExpressionBuilder::exprMitlRelease(), UTAP::ExpressionBuilder::exprMitlUntil(), UTAP::ExpressionBuilder::exprNary(), UTAP::ExpressionBuilder::exprNumOf(), UTAP::ExpressionBuilder::exprProbaCompare(), UTAP::ExpressionBuilder::exprProbaExpected(), UTAP::ExpressionBuilder::exprProbaQuantitative(), UTAP::ExpressionBuilder::exprSimulate(), UTAP::ExpressionBuilder::exprSMCControl(), UTAP::ExpressionBuilder::exprSpawn(), UTAP::StatementBuilder::exprStatement(), UTAP::ExpressionBuilder::exprSumDynamicEnd(), UTAP::SystemBuilder::exprSync(), UTAP::ExpressionBuilder::exprTernary(), UTAP::StatementBuilder::forEnd(), UTAP::SystemBuilder::ganttEntryEnd(), UTAP::StatementBuilder::ifEnd(), UTAP::SystemBuilder::instanceNameEnd(), UTAP::SystemBuilder::instantiationEnd(), UTAP::SystemBuilder::procCondition(), UTAP::SystemBuilder::procGuard(), UTAP::SystemBuilder::procLscUpdate(), UTAP::SystemBuilder::procMessage(), UTAP::SystemBuilder::procProb(), UTAP::SystemBuilder::procState(), UTAP::SystemBuilder::procSync(), UTAP::SystemBuilder::procUpdate(), UTAP::StatementBuilder::returnStatement(), UTAP::StatementBuilder::typeArrayOfSize(), UTAP::ExpressionBuilder::typeBoundedInt(), UTAP::ExpressionBuilder::typeScalar(), and UTAP::StatementBuilder::whileEnd().
void ExpressionBuilder::ExpressionFragments::pop (uint32_t n)
void UTAP::ExpressionBuilder::ExpressionFragments::push (expression_t e) inline
Referenced by UTAP::StatementBuilder::declInitialiserList(), UTAP::SystemBuilder::defaultChanPriority(), UTAP::ExpressionBuilder::exprArray(), UTAP::ExpressionBuilder::exprAssignment(), UTAP::ExpressionBuilder::exprBinary(), UTAP::ExpressionBuilder::exprCallEnd(), UTAP::ExpressionBuilder::exprComma(), UTAP::ExpressionBuilder::exprDeadlock(), UTAP::ExpressionBuilder::exprDouble(), UTAP::ExpressionBuilder::exprExistsDynamicEnd(), UTAP::ExpressionBuilder::exprExit(), UTAP::ExpressionBuilder::exprFalse(), UTAP::ExpressionBuilder::exprForAllDynamicEnd(), UTAP::ExpressionBuilder::exprForeachDynamicEnd(), UTAP::ExpressionBuilder::exprId(), UTAP::ExpressionBuilder::exprInlineIf(), UTAP::ExpressionBuilder::exprMitlAtom(), UTAP::ExpressionBuilder::exprMitlBox(), UTAP::ExpressionBuilder::exprMitlConj(), UTAP::ExpressionBuilder::exprMitlDiamond(), UTAP::ExpressionBuilder::exprMitlDisj(), UTAP::ExpressionBuilder::exprMitlFormula(), UTAP::ExpressionBuilder::exprMitlNext(), UTAP::ExpressionBuilder::exprMitlRelease(), UTAP::ExpressionBuilder::exprMitlUntil(), UTAP::ExpressionBuilder::exprNary(), UTAP::ExpressionBuilder::exprNat(), UTAP::ExpressionBuilder::exprNumOf(), UTAP::ExpressionBuilder::exprProbaCompare(), UTAP::ExpressionBuilder::exprProbaExpected(), UTAP::ExpressionBuilder::exprProbaQuantitative(), UTAP::ExpressionBuilder::exprScenario(), UTAP::ExpressionBuilder::exprSimulate(), UTAP::ExpressionBuilder::exprSMCControl(), UTAP::ExpressionBuilder::exprSpawn(), UTAP::ExpressionBuilder::exprSumDynamicEnd(), UTAP::ExpressionBuilder::exprTernary(), UTAP::ExpressionBuilder::exprTrue(), and UTAP::StatementBuilder::typeArrayOfSize().
uint32_t UTAP::ExpressionBuilder::ExpressionFragments::size () inline
The documentation for this class was generated from the following files:
expressionbuilder.h
expressionbuilder.cpp