libutap: UTAP::CaseStatement Class Reference
UTAP::CaseStatement Class Reference
#include <statement.h>
Public Member Functions
CaseStatement (frame_t, expression_t)
virtual int32_t accept (StatementVisitor *visitor)
virtual bool returns ()
std::string toString (std::string prefix) const
Public Member Functions inherited from UTAP::BlockStatement
BlockStatement (frame_t)
virtual ~BlockStatement ()
frame_t getFrame ()
void push_stat (Statement *stat)
Statement * pop_stat ()
Statement * back ()
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
Public Member Functions inherited from UTAP::Statement
virtual ~Statement ()
Public Member Functions inherited from UTAP::declarations_t
bool addFunction (type_t type, std::string, function_t *&)
Add function declaration.
std::string toString (bool global=false) const
The following methods are used to write the declarations in an XML file.
std::string getConstants () const
std::string getTypeDefinitions () const
std::string getVariables (bool global) const
std::string getFunctions () const
Public Attributes
expression_t cond
Public Attributes inherited from UTAP::declarations_t
frame_t frame
std::list< variable_t > variables
Variables.
std::list< function_t > functions
Functions.
std::list< progress_t > progress
Progress measures.
std::list< iodecl_t > iodecl
std::list< gantt_t > ganttChart
Additional Inherited Members
Public Types inherited from UTAP::BlockStatement
typedef std::vector< Statement * >
::const_iterator const_iterator
typedef std::vector< Statement * >
::iterator iterator
Protected Member Functions inherited from UTAP::Statement
Statement ()
Protected Attributes inherited from UTAP::BlockStatement
std::vector< Statement * > stats
frame_t frame
Constructor & Destructor Documentation
CaseStatement::CaseStatement (frame_t frame, expression_t cond)
Member Function Documentation
int32_t CaseStatement::accept (StatementVisitor * visitor) virtual
Reimplemented from UTAP::BlockStatement.
References UTAP::StatementVisitor::visitCaseStatement().
bool CaseStatement::returns () virtual
Reimplemented from UTAP::BlockStatement.
string CaseStatement::toString (std::string prefix) const virtual
Reimplemented from UTAP::BlockStatement.
References cond, INDENT, UTAP::expression_t::toString(), and UTAP::BlockStatement::toString().
Member Data Documentation
expression_t UTAP::CaseStatement::cond
Referenced by toString(), UTAP::SignalFlow::visitCaseStatement(), and UTAP::ExpressionVisitor::visitCaseStatement().
The documentation for this class was generated from the following files:
statement.h
statement.cpp