libutap: UTAP::SystemVisitor Class Reference
UTAP::SystemVisitor Class Reference
#include <system.h>
Public Member Functions
virtual ~SystemVisitor ()
virtual void visitSystemBefore (TimedAutomataSystem *)
virtual void visitSystemAfter (TimedAutomataSystem *)
virtual void visitVariable (variable_t &)
virtual bool visitTemplateBefore (template_t &)
virtual void visitTemplateAfter (template_t &)
virtual void visitState (state_t &)
virtual void visitEdge (edge_t &)
virtual void visitInstance (instance_t &)
virtual void visitProcess (instance_t &)
virtual void visitFunction (function_t &)
virtual void visitTypeDef (symbol_t)
virtual void visitIODecl (iodecl_t &)
virtual void visitProgressMeasure (progress_t &)
virtual void visitGanttChart (gantt_t &)
virtual void visitInstanceLine (instanceLine_t &)
virtual void visitMessage (message_t &)
virtual void visitCondition (condition_t &)
virtual void visitUpdate (update_t &)
Constructor & Destructor Documentation
virtual UTAP::SystemVisitor::~SystemVisitor () inline virtual
Member Function Documentation
virtual void UTAP::SystemVisitor::visitCondition (condition_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept(), and UTAP::TypeChecker::visitCondition().
virtual void UTAP::SystemVisitor::visitEdge (edge_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept(), and UTAP::TypeChecker::visitEdge().
virtual void UTAP::SystemVisitor::visitFunction (function_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by visit(), and UTAP::TypeChecker::visitFunction().
virtual void UTAP::SystemVisitor::visitGanttChart (gantt_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitInstance (instance_t &) inline virtual
Reimplemented in UTAP::TypeChecker, and UTAP::CompileTimeComputableValues.
Referenced by UTAP::TimedAutomataSystem::accept(), and UTAP::TypeChecker::visitInstance().
virtual void UTAP::SystemVisitor::visitInstanceLine (instanceLine_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by visit(), and UTAP::TypeChecker::visitInstanceLine().
virtual void UTAP::SystemVisitor::visitIODecl (iodecl_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitMessage (message_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept(), and UTAP::TypeChecker::visitMessage().
virtual void UTAP::SystemVisitor::visitProcess (instance_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitProgressMeasure (progress_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitState (state_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by visit(), and UTAP::TypeChecker::visitState().
virtual void UTAP::SystemVisitor::visitSystemAfter (TimedAutomataSystem *) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitSystemBefore (TimedAutomataSystem *) inline virtual
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitTemplateAfter (template_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual bool UTAP::SystemVisitor::visitTemplateBefore (template_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept().
virtual void UTAP::SystemVisitor::visitTypeDef (symbol_t) inline virtual
Referenced by visit().
virtual void UTAP::SystemVisitor::visitUpdate (update_t &) inline virtual
Reimplemented in UTAP::TypeChecker.
Referenced by UTAP::TimedAutomataSystem::accept(), and UTAP::TypeChecker::visitUpdate().
virtual void UTAP::SystemVisitor::visitVariable (variable_t &) inline virtual
Reimplemented in UTAP::TypeChecker, and UTAP::CompileTimeComputableValues.
Referenced by visit(), and UTAP::TypeChecker::visitVariable().
The documentation for this class was generated from the following file:
system.h