libutap: UTAP::StatementVisitor Class Reference
UTAP::StatementVisitor Class Reference abstract
#include <statement.h>
Public Member Functions
virtual ~StatementVisitor ()
virtual int32_t visitEmptyStatement (EmptyStatement *stat)=0
virtual int32_t visitExprStatement (ExprStatement *stat)=0
virtual int32_t visitAssertStatement (AssertStatement *stat)=0
virtual int32_t visitForStatement (ForStatement *stat)=0
virtual int32_t visitIterationStatement (IterationStatement *stat)=0
virtual int32_t visitWhileStatement (WhileStatement *stat)=0
virtual int32_t visitDoWhileStatement (DoWhileStatement *stat)=0
virtual int32_t visitBlockStatement (BlockStatement *stat)=0
virtual int32_t visitSwitchStatement (SwitchStatement *stat)=0
virtual int32_t visitCaseStatement (CaseStatement *stat)=0
virtual int32_t visitDefaultStatement (DefaultStatement *stat)=0
virtual int32_t visitIfStatement (IfStatement *stat)=0
virtual int32_t visitBreakStatement (BreakStatement *stat)=0
virtual int32_t visitContinueStatement (ContinueStatement *stat)=0
virtual int32_t visitReturnStatement (ReturnStatement *stat)=0
Constructor & Destructor Documentation
virtual UTAP::StatementVisitor::~StatementVisitor () inline virtual
Member Function Documentation
virtual int32_t UTAP::StatementVisitor::visitAssertStatement (AssertStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::AssertStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitBlockStatement (BlockStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::BlockStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitBreakStatement (BreakStatement * stat) pure virtual
Implemented in UTAP::AbstractStatementVisitor, and UTAP::SignalFlow.
Referenced by UTAP::BreakStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitCaseStatement (CaseStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, and UTAP::SignalFlow.
Referenced by UTAP::CaseStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitContinueStatement (ContinueStatement * stat) pure virtual
Implemented in UTAP::AbstractStatementVisitor, and UTAP::SignalFlow.
Referenced by UTAP::ContinueStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitDefaultStatement (DefaultStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, and UTAP::SignalFlow.
Referenced by UTAP::DefaultStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitDoWhileStatement (DoWhileStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::DoWhileStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitEmptyStatement (EmptyStatement * stat) pure virtual
Implemented in UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::EmptyStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitExprStatement (ExprStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::ExprStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitForStatement (ForStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::ForStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitIfStatement (IfStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::IfStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitIterationStatement (IterationStatement * stat) pure virtual
Implemented in UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::IterationStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitReturnStatement (ReturnStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::ReturnStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitSwitchStatement (SwitchStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, and UTAP::SignalFlow.
Referenced by UTAP::SwitchStatement::accept().
virtual int32_t UTAP::StatementVisitor::visitWhileStatement (WhileStatement * stat) pure virtual
Implemented in UTAP::ExpressionVisitor, UTAP::AbstractStatementVisitor, UTAP::SignalFlow, and UTAP::TypeChecker.
Referenced by UTAP::WhileStatement::accept().
The documentation for this class was generated from the following file:
statement.h