libutap: UTAP::XMLWriter Class Reference
UTAP::XMLWriter Class Reference
#include <xmlwriter.h>
Public Member Functions
void startDocument ()
void endDocument ()
void startElement (const char *element)
void endElement ()
void writeElement (const char *name, const char *content)
void writeAttribute (const char *name, const char *value)
void writeString (const char *content)
void xmlwriteString (const xmlChar *content)
void taTempl (const template_t &templ)
writes a template
void location (const state_t &state)
void init (const template_t &templ)
void name (const state_t &state, int x, int y)
void writeStateAttributes (const state_t &state, int x, int y)
void transition (const edge_t &edge)
void nail (int x, int y)
void label (const char *kind, std::string data, int x, int y)
int source (const edge_t &edge)
int target (const edge_t &edge)
void selfLoop (int loc, float initialAngle, const edge_t &edge)
void labels (int x, int y, const edge_t &edge)
void declaration ()
Parses optional declaration.
std::string getChanPriority () const
void parameter ()
void system_instantiation ()
XMLWriter (xmlTextWriterPtr writer, TimedAutomataSystem *taSystem)
virtual ~XMLWriter ()
void project ()
Parse the project document.
Public Attributes
xmlTextWriterPtr writer
The underlying xmlTextWriter.
TimedAutomataSystem * taSystem
The system to write.
std::map< int, int > selfLoops
Constructor & Destructor Documentation
XMLWriter::XMLWriter (xmlTextWriterPtr writer, TimedAutomataSystem * taSystem)
XMLWriter::~XMLWriter () virtual
References writer.
Member Function Documentation
void XMLWriter::declaration ()
Parses optional declaration.
References getChanPriority(), UTAP::TimedAutomataSystem::getGlobals(), taSystem, UTAP::declarations_t::toString(), and writeElement().
Referenced by project().
void XMLWriter::endDocument ()
References writer.
Referenced by project().
void XMLWriter::endElement ()
References writer.
Referenced by init(), label(), location(), nail(), name(), project(), source(), target(), taTempl(), and transition().
string XMLWriter::getChanPriority () const
References UTAP::TimedAutomataSystem::getChanPriorities(), and taSystem.
Referenced by declaration().
void XMLWriter::init (const template_t & templ)
References UTAP::concat(), endElement(), UTAP::symbol_t::getData(), UTAP::template_t::init, startElement(), and writeAttribute().
Referenced by taTempl().
void XMLWriter::label (const char * kind, std::string data, int x, int y)
References UTAP::concat(), UTAP::ConvertInput(), endElement(), MY_ENCODING, startElement(), writeAttribute(), and xmlwriteString().
Referenced by labels(), and location().
void XMLWriter::labels (int x, int y, const edge_t & edge)
References UTAP::edge_t::assign, UTAP::expression_t::empty(), UTAP::frame_t::getSize(), UTAP::edge_t::guard, label(), UTAP::edge_t::select, UTAP::edge_t::sync, and UTAP::expression_t::toString().
Referenced by selfLoop(), and transition().
void XMLWriter::location (const state_t & state)
References COMMITTED, UTAP::expression_t::empty(), endElement(), UTAP::symbol_t::getName(), UTAP::symbol_t::getType(), UTAP::state_t::invariant, UTAP::type_t::is(), label(), UTAP::state_t::locNr, name(), PINK, startElement(), STEP, UTAP::expression_t::toString(), UTAP::state_t::uid, URGENT, writeAttribute(), and writeStateAttributes().
Referenced by taTempl().
void XMLWriter::nail (int x, int y)
References UTAP::concat(), endElement(), startElement(), and writeAttribute().
Referenced by selfLoop(), and transition().
void XMLWriter::name (const state_t & state, int x, int y)
References UTAP::concat(), endElement(), UTAP::symbol_t::getName(), startElement(), UTAP::state_t::uid, writeAttribute(), and writeString().
Referenced by location(), and taTempl().
void UTAP::XMLWriter::parameter ()
void XMLWriter::project ()
Parse the project document.
References declaration(), endDocument(), endElement(), UTAP::TimedAutomataSystem::getTemplates(), startDocument(), startElement(), system_instantiation(), taSystem, and taTempl().
Referenced by writeXMLFile().
void XMLWriter::selfLoop (int loc, float initialAngle, const edge_t & edge)
References labels(), nail(), PI, RADIUS, selfLoops, STEP, x1, and y1.
Referenced by transition().
int XMLWriter::source (const edge_t & edge)
References UTAP::concat(), endElement(), UTAP::state_t::locNr, UTAP::edge_t::src, startElement(), and writeAttribute().
Referenced by transition().
void XMLWriter::startDocument ()
References MY_ENCODING, and writer.
Referenced by project().
void XMLWriter::startElement (const char * element)
References writer.
Referenced by init(), label(), location(), nail(), name(), project(), source(), target(), taTempl(), and transition().
void XMLWriter::system_instantiation ()
References UTAP::TimedAutomataSystem::getProcesses(), taSystem, and writeElement().
Referenced by project().
int XMLWriter::target (const edge_t & edge)
References UTAP::concat(), UTAP::edge_t::dst, endElement(), UTAP::state_t::locNr, startElement(), and writeAttribute().
Referenced by transition().
void XMLWriter::taTempl (const template_t & templ)
writes a template
References UTAP::template_t::edges, endElement(), UTAP::symbol_t::getName(), init(), UTAP::template_t::isTA, location(), name(), selfLoops, startElement(), UTAP::template_t::states, UTAP::declarations_t::toString(), transition(), UTAP::instance_t::uid, writeElement(), and UTAP::instance_t::writeParameters().
Referenced by project().
void XMLWriter::transition (const edge_t & edge)
References endElement(), UTAP::symbol_t::getName(), labels(), nail(), PI, selfLoop(), source(), UTAP::edge_t::src, startElement(), STEP, target(), and UTAP::state_t::uid.
Referenced by taTempl().
void XMLWriter::writeAttribute (const char * name, const char * value)
References writer.
Referenced by init(), label(), location(), nail(), name(), source(), target(), and writeStateAttributes().
void XMLWriter::writeElement (const char * name, const char * content)
References writer.
Referenced by declaration(), system_instantiation(), and taTempl().
void XMLWriter::writeStateAttributes (const state_t & state, int x, int y)
References UTAP::concat(), UTAP::state_t::locNr, and writeAttribute().
Referenced by location().
void XMLWriter::writeString (const char * content)
References writer.
Referenced by name().
void XMLWriter::xmlwriteString (const xmlChar * content)
References writer.
Referenced by label().
Member Data Documentation
std::map<int, int> UTAP::XMLWriter::selfLoops
Referenced by selfLoop(), and taTempl().
TimedAutomataSystem* UTAP::XMLWriter::taSystem
The system to write.
Referenced by declaration(), getChanPriority(), project(), and system_instantiation().
xmlTextWriterPtr UTAP::XMLWriter::writer
The underlying xmlTextWriter.
Referenced by endDocument(), endElement(), startDocument(), startElement(), writeAttribute(), writeElement(), writeString(), xmlwriteString(), and ~XMLWriter().
The documentation for this class was generated from the following files:
xmlwriter.h
xmlwriter.cpp