libutap: expression.cpp File Reference
expression.cpp File Reference
#include <cassert>
#include <algorithm>
#include <stdexcept>
#include "utap/builder.h"
#include "utap/system.h"
#include "utap/expression.h"
#include <string.h>
Functions
static void ensure (char *&str, char *&end, int &size, int len)
static void append (char *&str, char *&end, int &size, const char *s)
static void append (char *&str, char *&end, int &size, char c)
ostream & operator<< (ostream &o, const expression_t &e)
Function Documentation
static void append (char *& str, char *& end, int & size, const char * s) static
References ensure().
static void append (char *& str, char *& end, int & size, char c) static
References ensure().
static void ensure (char *& str, char *& end, int & size, int len) static
Referenced by append().
ostream& operator<< (ostream & o, const expression_t & e)
References UTAP::expression_t::toString().