libutap: expressionbuilder.cpp File Reference
expressionbuilder.cpp File Reference
#include <vector>
#include <climits>
#include <cmath>
#include <cstdio>
#include <cassert>
#include <inttypes.h>
#include <string.h>
#include <boost/format.hpp>
#include "utap/expressionbuilder.h"
Macros
#define defaultIntMin -0x7FFF
#define defaultIntMax 0x7FFF
Functions
bool isMITL (expression_t e)
expression_t toMITLAtom (expression_t e)
static void collectDependencies (std::set< symbol_t > &dependencies, expression_t expr)
Macro Definition Documentation
#define defaultIntMax 0x7FFF
Referenced by UTAP::ExpressionBuilder::typeInt().
#define defaultIntMin -0x7FFF
Referenced by UTAP::ExpressionBuilder::typeInt().
Function Documentation
static void collectDependencies (std::set< symbol_t > & dependencies, expression_t expr) static
References UTAP::expression_t::collectPossibleReads(), UTAP::variable_t::expr, and UTAP::symbol_t::getData().
Referenced by UTAP::ExpressionBuilder::typeScalar().
bool isMITL (expression_t e)
References UTAP::expression_t::getKind(), UTAP::Constants::MITLATOM, UTAP::Constants::MITLCONJ, UTAP::Constants::MITLDISJ, UTAP::Constants::MITLEXISTS, UTAP::Constants::MITLFORALL, UTAP::Constants::MITLFORMULA, UTAP::Constants::MITLNEXT, UTAP::Constants::MITLRELEASE, and UTAP::Constants::MITLUNTIL.
Referenced by UTAP::ExpressionBuilder::exprBinary(), UTAP::ExpressionBuilder::exprExistsDynamicEnd(), UTAP::ExpressionBuilder::exprForAllDynamicEnd(), UTAP::ExpressionBuilder::exprMitlAtom(), UTAP::ExpressionBuilder::exprMitlBox(), UTAP::ExpressionBuilder::exprMitlDiamond(), UTAP::ExpressionBuilder::exprMitlFormula(), UTAP::ExpressionBuilder::exprMitlNext(), UTAP::ExpressionBuilder::exprMitlRelease(), and UTAP::ExpressionBuilder::exprMitlUntil().
expression_t toMITLAtom (expression_t e)
References UTAP::expression_t::createUnary(), and UTAP::Constants::MITLATOM.
Referenced by UTAP::ExpressionBuilder::exprBinary(), UTAP::ExpressionBuilder::exprMitlBox(), UTAP::ExpressionBuilder::exprMitlDiamond(), UTAP::ExpressionBuilder::exprMitlFormula(), UTAP::ExpressionBuilder::exprMitlNext(), UTAP::ExpressionBuilder::exprMitlRelease(), and UTAP::ExpressionBuilder::exprMitlUntil().