libutap: lexer.cc File Reference
lexer.cc File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <iostream>
#include "keywords.cc"
#include "libparser.h"
#include <unistd.h>
Namespaces
UTAP
Macros
#define YY_INT_ALIGNED short int
#define yy_create_buffer utap__create_buffer
#define yy_delete_buffer utap__delete_buffer
#define yy_flex_debug utap__flex_debug
#define yy_init_buffer utap__init_buffer
#define yy_flush_buffer utap__flush_buffer
#define yy_load_buffer_state utap__load_buffer_state
#define yy_switch_to_buffer utap__switch_to_buffer
#define yyin utap_in
#define yyleng utap_leng
#define yylex utap_lex
#define yylineno utap_lineno
#define yyout utap_out
#define yyrestart utap_restart
#define yytext utap_text
#define yywrap utap_wrap
#define yyalloc utap_alloc
#define yyrealloc utap_realloc
#define yyfree utap_free
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define BEGIN (yy_start) = 1 + 2 *
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE utap_restart(utap_in)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)
#define yyless(n)
#define unput(c) yyunput(c, (yytext_ptr))
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
#define YY_FLUSH_BUFFER utap__flush_buffer(YY_CURRENT_BUFFER)
#define yy_new_buffer utap__create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yytext_ptr utap_text
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_DECL int lexer_flex(void)
#define YY_USER_ACTION yylloc.start = PositionTracker::position; PositionTracker::increment(ch, utap_leng); yylloc.end = PositionTracker::position;
#define YY_FATAL_ERROR(msg) { throw TypeException(msg); }
#define INITIAL 0
#define comment 1
#define YY_EXTRA_TYPE void *
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(utap_text, utap_leng, 1, utap_out)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void utap_restart (FILE *input_file)
void utap__switch_to_buffer (YY_BUFFER_STATE new_buffer)
YY_BUFFER_STATE utap__create_buffer (FILE *file, int size)
void utap__delete_buffer (YY_BUFFER_STATE b)
void utap__flush_buffer (YY_BUFFER_STATE b)
void utap_push_buffer_state (YY_BUFFER_STATE new_buffer)
void utap_pop_buffer_state (void)
static void utap_ensure_buffer_stack (void)
static void utap__load_buffer_state (void)
static void utap__init_buffer (YY_BUFFER_STATE b, FILE *file)
YY_BUFFER_STATE utap__scan_buffer (char *base, yy_size_t size)
YY_BUFFER_STATE utap__scan_string (yyconst char *yy_str)
YY_BUFFER_STATE utap__scan_bytes (yyconst char *bytes, yy_size_t len)
void * utap_alloc (yy_size_t)
void * utap_realloc (void *, yy_size_t)
void utap_free (void *)
static yy_state_type yy_get_previous_state (void)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state)
static int yy_get_next_buffer (void)
static void yy_fatal_error (yyconst char msg[])
static int yy_init_globals (void)
int utap_lex_destroy (void)
int utap_get_debug (void)
void utap_set_debug (int debug_flag)
YY_EXTRA_TYPE utap_get_extra (void)
void utap_set_extra (YY_EXTRA_TYPE user_defined)
FILE * utap_get_in (void)
void utap_set_in (FILE *in_str)
FILE * utap_get_out (void)
void utap_set_out (FILE *out_str)
yy_size_t utap_get_leng (void)
char * utap_get_text (void)
int utap_get_lineno (void)
void utap_set_lineno (int line_number)
int utap_wrap (void)
static int input (void)
if (!(yy_init))
Variables
yy_size_t utap_leng
FILE * utap_in = (FILE *) 0
FILE * utap_out = (FILE *) 0
static size_t yy_buffer_stack_top = 0
index of top of stack.
static size_t yy_buffer_stack_max = 0
capacity of stack.
static YY_BUFFER_STATE * yy_buffer_stack = 0
Stack as an array.
static char yy_hold_char
static yy_size_t yy_n_chars
static char * yy_c_buf_p = (char *) 0
static int yy_init = 0
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
int utap_lineno = 1
char * utap_text
static yyconst flex_int16_t yy_accept [110]
static yyconst flex_int32_t yy_ec [256]
static yyconst flex_int32_t yy_meta [41]
static yyconst flex_int16_t yy_base [113]
static yyconst flex_int16_t yy_def [113]
static yyconst flex_int16_t yy_nxt [180]
static yyconst flex_int16_t yy_chk [180]
static yy_state_type yy_last_accepting_state
static char * yy_last_accepting_cpos
int utap__flex_debug = 0
YY_DECL
The main scanner function which does all the work.
register char * yy_cp
register char * yy_bp
register int yy_act
Macro Definition Documentation
#define BEGIN (yy_start) = 1 + 2 *
#define comment 1
Referenced by UTAP::SystemBuilder::queryComment().
#define ECHO do { if (fwrite(utap_text, utap_leng, 1, utap_out)) {} } while (0)
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define FLEX_BETA
#define FLEX_SCANNER
#define FLEXINT_H
#define INITIAL 0
#define INT16_MAX (32767)
#define INT16_MIN (-32767-1)
#define INT32_MAX (2147483647)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT8_MIN (-128)
#define REJECT reject_used_but_not_detected
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define UINT8_MAX (255U)
#define unput (c) yyunput(c, (yytext_ptr))
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define YY_BREAK break;
#define YY_BUF_SIZE 16384
Referenced by if(), parseProperty(), and parseXTA().
#define YY_BUFFER_EOF_PENDING 2
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define yy_create_buffer utap__create_buffer
#define YY_CURRENT_BUFFER
Value:
((yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
Referenced by if(), parseProperty(), and parseXTA().
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
Referenced by if().
#define YY_DECL int lexer_flex(void)
#define yy_delete_buffer utap__delete_buffer
#define YY_DO_BEFORE_ACTION
Value:
(yytext_ptr) = yy_bp; \
    utap_leng = (size_t) (yy_cp - yy_bp); \
        (yy_hold_char) = *yy_cp; \
        *yy_cp = '\0'; \
        (yy_c_buf_p) = yy_cp;
#define YY_END_OF_BUFFER 86
#define YY_END_OF_BUFFER_CHAR 0
#define YY_EXIT_FAILURE 2
#define YY_EXTRA_TYPE void *
#define YY_FATAL_ERROR (msg) { throw TypeException(msg); }
#define yy_flex_debug utap__flex_debug
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#define yy_flush_buffer utap__flush_buffer
#define YY_FLUSH_BUFFER utap__flush_buffer(YY_CURRENT_BUFFER)
#define yy_init_buffer utap__init_buffer
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
                { \
                int c = '*'; \
                size_t n; \
                for ( n = 0; n < max_size && \
                             (c = getc( utap_in )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( utap_in ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                errno=0; \
                while ( (result = fread(buf, 1, max_size, utap_in))==0 && ferror(utap_in)) \
                        { \
            if( errno != EINTR) \
                                { \
                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(utap_in); \
                        } \
                }\
\
#define YY_INT_ALIGNED short int
#define YY_LESS_LINENO (n)
#define YY_LINENO_REWIND_TO (ptr)
#define yy_load_buffer_state utap__load_buffer_state
#define YY_MORE_ADJ 0
#define yy_new_buffer utap__create_buffer
#define YY_NEW_FILE utap_restart(utap_in)
#define YY_NULL 0
#define YY_NUM_RULES 85
#define YY_READ_BUF_SIZE 8192
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
#define yy_set_bol (at_bol)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){\
        utap_ensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            utap__create_buffer(utap_in,YY_BUF_SIZE ); \
        } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
#define yy_set_interactive (is_interactive)
Value:
{ \
    if ( ! YY_CURRENT_BUFFER ){ \
        utap_ensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            utap__create_buffer(utap_in,YY_BUF_SIZE ); \
        } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
#define YY_START (((yy_start) - 1) / 2)
#define YY_START_STACK_INCR 25
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
#define YY_STRUCT_YY_BUFFER_STATE
#define yy_switch_to_buffer utap__switch_to_buffer
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define YY_USER_ACTION yylloc.start = PositionTracker::position; PositionTracker::increment(ch, utap_leng); yylloc.end = PositionTracker::position;
#define yyalloc utap_alloc
Referenced by yyparse().
#define yyconst
#define yyfree utap_free
#define yyin utap_in
#define yyleng utap_leng
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up utap_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = (yy_hold_char); \
        YY_RESTORE_YY_MORE_OFFSET \
                (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up utap_text again */ \
                } \
        while ( 0 )
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up utap_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        utap_text[utap_leng] = (yy_hold_char); \
                (yy_c_buf_p) = utap_text + yyless_macro_arg; \
                (yy_hold_char) = *(yy_c_buf_p); \
                *(yy_c_buf_p) = '\0'; \
        utap_leng = yyless_macro_arg; \
                } \
        while ( 0 )
#define yylex utap_lex
#define yylineno utap_lineno
#define yymore () yymore_used_but_not_detected
#define yyout utap_out
#define yyrealloc utap_realloc
#define yyrestart utap_restart
#define YYSTATE YY_START
#define YYTABLES_NAME "yytables"
#define yyterminate () return YY_NULL
#define yytext utap_text
#define yytext_ptr utap_text
#define yywrap utap_wrap
Typedef Documentation
typedef short int flex_int16_t
typedef int flex_int32_t
typedef signed char flex_int8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef unsigned char flex_uint8_t
typedef struct yy_buffer_state* YY_BUFFER_STATE
typedef unsigned char YY_CHAR
typedef size_t yy_size_t
typedef int yy_state_type
Function Documentation
if (! yy_init)
References utap__create_buffer(), utap__load_buffer_state(), utap_ensure_buffer_stack(), utap_in, utap_out, YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init, and yy_start.
static int input (void) static
YY_BUFFER_STATE utap__create_buffer (FILE * file, int size)
Referenced by if(), parseProperty(), and parseXTA().
void utap__delete_buffer (YY_BUFFER_STATE b)
Referenced by parseProperty(), and parseXTA().
void utap__flush_buffer (YY_BUFFER_STATE b)
static void utap__init_buffer (YY_BUFFER_STATE b, FILE * file) static
static void utap__load_buffer_state (void) static
Referenced by if().
YY_BUFFER_STATE utap__scan_buffer (char * base, yy_size_t size)
YY_BUFFER_STATE utap__scan_bytes (yyconst char * bytes, yy_size_t len)
YY_BUFFER_STATE utap__scan_string (yyconst char * yy_str)
Referenced by parseProperty(), and parseXTA().
void utap__switch_to_buffer (YY_BUFFER_STATE new_buffer)
Referenced by parseProperty(), and parseXTA().
void* utap_alloc (yy_size_t)
static void utap_ensure_buffer_stack (void) static
Referenced by if().
void utap_free (void *)
int utap_get_debug (void)
YY_EXTRA_TYPE utap_get_extra (void)
FILE* utap_get_in (void)
yy_size_t utap_get_leng (void)
int utap_get_lineno (void)
FILE* utap_get_out (void)
char* utap_get_text (void)
int utap_lex_destroy (void)
void utap_pop_buffer_state (void)
void utap_push_buffer_state (YY_BUFFER_STATE new_buffer)
void* utap_realloc (void * , yy_size_t)
void utap_restart (FILE * input_file)
void utap_set_debug (int debug_flag)
void utap_set_extra (YY_EXTRA_TYPE user_defined)
void utap_set_in (FILE * in_str)
void utap_set_lineno (int line_number)
void utap_set_out (FILE * out_str)
int utap_wrap (void)
static void yy_fatal_error (yyconst char msg[]) static
static int yy_get_next_buffer (void) static
static yy_state_type yy_get_previous_state (void) static
static int yy_init_globals (void) static
static yy_state_type yy_try_NUL_trans (yy_state_type current_state) static
Variable Documentation
int utap__flex_debug = 0
FILE * utap_in = (FILE *) 0
Referenced by if().
yy_size_t utap_leng
int utap_lineno = 1
FILE * utap_out = (FILE *) 0
Referenced by if().
char * utap_text
yyconst flex_int16_t yy_accept[110] static
Initial value:
=
    {   0,
        0,    0,    0,    0,   86,   84,    6,    8,   84,   22,
       80,   44,   46,   21,   18,   19,   42,   40,   11,   41,
       10,   43,   82,   13,   12,   58,   26,   59,   20,   64,
       81,   68,   66,   65,   67,   16,   23,   17,   47,   14,
       45,   15,    3,    1,    3,    6,    8,    9,   61,   32,
       51,   34,   30,   62,   28,   63,   29,   24,    0,    7,
        5,   31,   52,    0,   82,    0,   27,   48,   54,   79,
       38,   56,   60,   57,   55,   49,   39,   81,    0,    0,
        0,    0,   78,    0,    4,   53,   35,   33,   50,    2,
        0,   73,    0,    5,   83,    0,   83,   36,   37,   69,
       70,   71,   72,   25,   76,   74,   77,   75,    0
    }
register int yy_act
yyconst flex_int16_t yy_base[113] static
Initial value:
=
    {   0,
        0,    0,   38,   39,  138,  139,  135,  133,  132,  111,
      139,  110,   34,  139,  139,  139,  109,   30,  139,   31,
      139,   43,   31,  108,  139,   40,   47,   49,  139,   53,
       55,   56,   57,   58,   59,   96,   80,  139,  106,  139,
       61,  139,  139,  139,  110,  125,  123,  121,  139,  139,
      139,  139,  139,  139,  139,  100,  139,  139,  107,  139,
        0,  139,  139,  103,   75,   83,  139,   98,  139,  139,
      139,  139,  139,  139,  139,   97,  139,   64,   95,   83,
       86,   75,  139,   43,  139,  139,  139,  139,  139,  139,
       98,  139,   69,    0,   76,   41,   39,  139,  139,  139,
       92,   94,  139,  139,  139,  139,  139,  139,  139,  112,
       46,  115
    }
register char * yy_bp
YY_BUFFER_STATE* yy_buffer_stack = 0 static
Stack as an array.
size_t yy_buffer_stack_max = 0 static
capacity of stack.
size_t yy_buffer_stack_top = 0 static
index of top of stack.
char* yy_c_buf_p = (char *) 0 static
yyconst flex_int16_t yy_chk[180] static
Initial value:
=
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   13,   18,   84,   84,   20,   23,  111,   23,
        3,    4,   18,   20,   20,   22,   13,   97,   23,   96,
       22,   26,   26,   26,   26,   22,   23,   20,   27,   27,
       27,   28,   28,   28,   30,   22,   31,   32,   33,   34,
       35,   37,   37,   41,   30,   78,   31,   32,   33,   34,
       35,   65,   93,   65,   95,   78,   66,   37,   66,   41,
       91,   66,   65,   95,  101,  101,  102,  102,   82,   81,
       65,   95,  110,  110,  110,  112,   80,  112,   79,   76,
       68,   64,   59,   56,   48,   47,   46,   45,   39,   36,
       24,   17,   12,   10,    9,    8,    7,    5,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109
    }
register char* yy_cp
YY_DECL
Initial value:
{
        register yy_state_type yy_current_state
The main scanner function which does all the work.
yyconst flex_int16_t yy_def[113] static
Initial value:
=
    {   0,
      109,    1,  110,  110,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  111,
      111,  111,  111,  111,  111,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      112,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  111,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  112,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,    0,  109,
      109,  109
    }
int yy_did_buffer_switch_on_eof static
yyconst flex_int32_t yy_ec[256] static
char yy_hold_char static
int yy_init = 0 static
Referenced by if().
char* yy_last_accepting_cpos static
yy_state_type yy_last_accepting_state static
yyconst flex_int32_t yy_meta[41] static
Initial value:
=
    {   0,
        1,    1,    2,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    3,    3,    1,    1,    1
    }
yy_size_t yy_n_chars static
yyconst flex_int16_t yy_nxt[180] static
Initial value:
=
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   31,   31,   40,   41,   42,
       44,   44,   51,   54,   84,   85,   56,   64,   78,   65,
       45,   45,   55,   57,   58,   60,   52,   97,   66,   97,
       61,   68,   69,   70,   71,   62,   66,   59,   72,   73,
       74,   75,   76,   77,   79,   63,  109,   81,  109,  109,
      109,   84,   85,   88,   80,  109,  109,   82,  109,  109,
      109,   64,  104,   65,   95,  109,   96,   86,   96,   89,
       48,   97,   66,   66,  105,  106,  107,  108,  103,  102,
       66,   66,   43,   43,   43,   94,  101,   94,  100,   99,
       98,   95,   93,   92,   91,   47,   46,   90,   87,   83,
       67,   53,   50,   49,   48,   47,   46,  109,    5,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109
    }
int yy_start = 0 static
Referenced by if().