libutap: UTAP Namespace Reference
UTAP Namespace Reference
Namespaces
Constants
Classes
class AbstractBuilder
class AbstractStatementVisitor
class AssertStatement
class BlockStatement
struct branchpoint_t
Information about a branchpoint.
class BreakStatement
class CaseStatement
struct chan_priority_t
Channel priority information.
class CollectChangesVisitor
class CollectDependenciesVisitor
class CollectDynamicExpressions
struct compare_simregion
class CompileTimeComputableValues
Visitor which collects all compile time computable symbols.
struct condition_t
Information about a condition.
class ContinueStatement
struct cut_t
struct declarations_t
class DefaultStatement
class DistanceCalculator
DistanceCalculator is used in TargetFirst heuristic search order of Uppaal.
class DoWhileStatement
struct edge_t
Information about an edge.
class EmptyStatement
struct error_t
class expression_t
A reference to an expression.
class ExpressionBuilder
Partial implementation of the builder interface: The ExpressionBuilder implements all expression related methods.
class ExpressionVisitor
class ExprStatement
class ForStatement
class frame_t
A reference to a frame.
struct function_t
Information about a function.
struct gantt_t
Gantt chart entry.
struct ganttmap_t
Gantt map bool expr -> int expr that can be expanded.
class IfStatement
struct instance_t
Partial instance of a template.
struct instanceLine_t
Information about an instance line.
struct iodecl_t
class IterationStatement
Statement class for the iterator loop-construction.
struct message_t
Information about a message.
class NoParentException
class NotSupportedException
class ParserBuilder
The ParserBuilder interface is used by the parser to output the parsed system.
class Partitioner
Partitions the system into environment and IUT according to TRON assumptions.
struct position_t
class Positions
A container for information about lines and positions in the input file.
class PositionTracker
Help class used by the lexer, parser and xmlreader to keep track of the current position.
class PrettyPrinter
struct print
print – template for pretty printing lists.
struct progress_t
struct query_t
class range_t
An integer range.
class ReturnStatement
class SBMLConverter
class SignalFlow
Class SignalFlow is for analysing UPPAAL specifications and extracting the timed automata input/output "interface" information which can be treated as a data flow or entity-relationship map of the system.
struct simregion_t
struct state_t
Information about a location.
class Statement
class StatementBuilder
Partial implementation of the builder interface, useful for building something with statements that is not a UTAP system.
class StatementVisitor
class SwitchStatement
class symbol_t
A reference to a symbol.
class SystemBuilder
This class constructs a TimedAutomataSystem.
class SystemVisitor
struct template_t
class TimedAutomataSystem
class type_t
A reference to a type.
class TypeChecker
A visitor which type checks the system it visits.
class TypeException
Exception indicating a type error.
struct update_t
Information about an update.
struct variable_t
Base type for variables, clocks, etc.
class WhileStatement
class XMLWriter
Typedefs
typedef std::vector< query_t > queries_t
Enumerations
enum xta_part_t {
S_XTA, S_DECLARATION, S_LOCAL_DECL, S_INST,
S_SYSTEM, S_PARAMETERS, S_INVARIANT, S_EXPONENTIALRATE,
S_SELECT, S_GUARD, S_SYNC, S_ASSIGN,
S_EXPRESSION, S_EXPRESSION_LIST, S_PROPERTY, S_XTA_PROCESS,
S_PROBABILITY, S_INSTANCELINE, S_MESSAGE, S_UPDATE,
S_CONDITION
}
Type for specifying which XTA part to parse (syntax switch)
enum tag_t {
TAG_NTA, TAG_IMPORTS, TAG_DECLARATION, TAG_TEMPLATE,
TAG_INSTANTIATION, TAG_SYSTEM, TAG_NAME, TAG_PARAMETER,
TAG_LOCATION, TAG_INIT, TAG_TRANSITION, TAG_URGENT,
TAG_COMMITTED, TAG_BRANCHPOINT, TAG_SOURCE, TAG_TARGET,
TAG_LABEL, TAG_NAIL, TAG_NONE, TAG_PROJECT,
TAG_LSC, TAG_TYPE, TAG_MODE, TAG_ROLE,
TAG_YLOCCOORD, TAG_LSCLOCATION, TAG_PRECHART, TAG_INSTANCE,
TAG_TEMPERATURE, TAG_MESSAGE, TAG_CONDITION, TAG_UPDATE,
TAG_ANCHOR, TAG_SBML, TAG_QUERIES, TAG_QUERY,
TAG_FORMULA, TAG_COMMENT
}
Enumeration type for tags.
Functions
std::ostream & operator<< (std::ostream &os, const SignalFlow::strs_t &s)
std::ostream & operator<< (std::ostream &os, const SignalFlow::procs_t &ps)
xmlChar * ConvertInput (const char *in, const char *encoding)
ConvertInput: : string in a given encoding : the encoding used.
std::string concat (std::string s, int i)
concatenates a string and an int
std::string concatDouble (std::string s, double i)
concatenates a string and a double
static bool isempty (string str)
Returns TRUE if string is zero length or contains only white spaces otherwise FALSE.
static bool isAlpha (unsigned char c)
static bool isIdChr (unsigned char c)
static string symbol (const char *str)
Extracts the alpha-numerical symbol used for variable/type identifiers.
Typedef Documentation
typedef std::vector<query_t> UTAP::queries_t
Enumeration Type Documentation
enum UTAP::tag_t
Enumeration type for tags.
We use gperf to generate a perfect hash function to map tag strings to one of these tags.
Enumerator
TAG_NTA
TAG_IMPORTS
TAG_DECLARATION
TAG_TEMPLATE
TAG_INSTANTIATION
TAG_SYSTEM
TAG_NAME
TAG_PARAMETER
TAG_LOCATION
TAG_INIT
TAG_TRANSITION
TAG_URGENT
TAG_COMMITTED
TAG_BRANCHPOINT
TAG_SOURCE
TAG_TARGET
TAG_LABEL
TAG_NAIL
TAG_NONE
TAG_PROJECT
TAG_LSC
TAG_TYPE
TAG_MODE
TAG_ROLE
TAG_YLOCCOORD
TAG_LSCLOCATION
TAG_PRECHART
TAG_INSTANCE
TAG_TEMPERATURE
TAG_MESSAGE
TAG_CONDITION
TAG_UPDATE
TAG_ANCHOR
TAG_SBML
TAG_QUERIES
TAG_QUERY
TAG_FORMULA
TAG_COMMENT
enum UTAP::xta_part_t
Type for specifying which XTA part to parse (syntax switch)
Enumerator
S_XTA
S_DECLARATION
S_LOCAL_DECL
S_INST
S_SYSTEM
S_PARAMETERS
S_INVARIANT
S_EXPONENTIALRATE
S_SELECT
S_GUARD
S_SYNC
S_ASSIGN
S_EXPRESSION
S_EXPRESSION_LIST
S_PROPERTY
S_XTA_PROCESS
S_PROBABILITY
S_INSTANCELINE
S_MESSAGE
S_UPDATE
S_CONDITION
Function Documentation
std::string UTAP::concat (std::string s, int i)
concatenates a string and an int
Referenced by UTAP::XMLWriter::init(), UTAP::XMLWriter::label(), UTAP::XMLWriter::nail(), UTAP::XMLWriter::name(), UTAP::XMLWriter::source(), UTAP::XMLWriter::target(), and UTAP::XMLWriter::writeStateAttributes().
std::string UTAP::concatDouble (std::string s, double i)
concatenates a string and a double
xmlChar * UTAP::ConvertInput (const char * in, const char * encoding)
ConvertInput: : string in a given encoding : the encoding used.
Converts into UTF-8 for processing with libxml2 APIs
Returns the converted UTF-8 string, or NULL in case of error.
Referenced by UTAP::XMLWriter::label().
static bool UTAP::isAlpha (unsigned char c) static
Referenced by symbol().
static bool UTAP::isempty (string str) static
Returns TRUE if string is zero length or contains only white spaces otherwise FALSE.
static bool UTAP::isIdChr (unsigned char c) static
Referenced by symbol().
std::ostream& UTAP::operator<< (std::ostream & os, const SignalFlow::strs_t & s) inline
std::ostream& UTAP::operator<< (std::ostream & os, const SignalFlow::procs_t & ps) inline
static string UTAP::symbol (const char * str) static
Extracts the alpha-numerical symbol used for variable/type identifiers.
Identifier starts with alpha and further might contain digits, white spaces are ignored.
Throws a TypeException is identifier is invalid or a newly allocated string to be destroyed with delete [].
References isAlpha(), and isIdChr().
Referenced by UTAP::frame_t::addSymbol(), UTAP::expression_t::collectPossibleReads(), UTAP::expression_t::collectPossibleWrites(), UTAP::expression_t::createIdentifier(), UTAP::ExpressionBuilder::exprForAllBegin(), UTAP::frame_t::moveTo(), UTAP::SystemBuilder::process(), UTAP::SystemBuilder::procPriority(), UTAP::frame_t::remove(), and UTAP::TypeChecker::visitBlockStatement().