libutap: statementbuilder.cpp File Reference
statementbuilder.cpp File Reference
#include <vector>
#include <climits>
#include <cmath>
#include <cstdio>
#include <cassert>
#include <inttypes.h>
#include <stdexcept>
#include <sstream>
#include <boost/tuple/tuple.hpp>
#include "utap/statementbuilder.h"
Functions
static bool initRec (type_t type, int thisTypeOnly)
static bool initialisable (type_t type)
static bool mustInitialise (type_t type)
Function Documentation
static bool initialisable (type_t type) static
References initRec().
Referenced by UTAP::StatementBuilder::declVar().
static bool initRec (type_t type, int thisTypeOnly) static
References UTAP::Constants::ARRAY, UTAP::type_t::getArraySize(), UTAP::type_t::getKind(), UTAP::type_t::getSub(), UTAP::type_t::isClock(), UTAP::type_t::isDouble(), UTAP::type_t::isIntegral(), UTAP::type_t::isScalar(), UTAP::Constants::RECORD, UTAP::type_t::size(), and UTAP::type_t::strip().
Referenced by initialisable().
static bool mustInitialise (type_t type) static
References UTAP::Constants::CONSTANT, UTAP::Constants::FUNCTION, UTAP::type_t::getKind(), UTAP::Constants::INSTANCE, UTAP::Constants::LSCINSTANCE, UTAP::Constants::PROCESS, UTAP::Constants::RECORD, and UTAP::type_t::size().
Referenced by UTAP::StatementBuilder::declVar().