libutap: UTAP::simregion_t Struct Reference
UTAP::simregion_t Struct Reference
#include <system.h>
Public Member Functions
int getLoc () const
May be empty.
bool isInPrechart () const
simregion_t ()
~simregion_t ()
std::string toString () const
void setMessage (std::deque< message_t > &messages, int nr)
void setCondition (std::deque< condition_t > &conditions, int nr)
void setUpdate (std::deque< update_t > &updates, int nr)
Public Attributes
int nr
message_t * message
condition_t * condition
May be empty.
update_t * update
May be empty.
Constructor & Destructor Documentation
UTAP::simregion_t::simregion_t () inline
UTAP::simregion_t::~simregion_t () inline
References condition, message, and update.
Member Function Documentation
int simregion_t::getLoc () const
May be empty.
References UTAP::update_t::location, and UTAP::update_t::nr.
Referenced by UTAP::compare_simregion::operator()().
bool simregion_t::isInPrechart () const
References UTAP::update_t::isInPrechart, and UTAP::update_t::nr.
Referenced by UTAP::cut_t::isInPrechart().
void simregion_t::setCondition (std::deque< condition_t > & conditions, int nr)
Referenced by UTAP::template_t::getSimregions().
void simregion_t::setMessage (std::deque< message_t > & messages, int nr)
Referenced by UTAP::template_t::getSimregions().
void simregion_t::setUpdate (std::deque< update_t > & updates, int nr)
Referenced by UTAP::template_t::getSimregions().
std::string simregion_t::toString () const
References UTAP::update_t::label, UTAP::update_t::nr, and UTAP::expression_t::toString().
Member Data Documentation
condition_t* UTAP::simregion_t::condition
May be empty.
Referenced by UTAP::template_t::getSimregions(), and ~simregion_t().
message_t* UTAP::simregion_t::message
Referenced by UTAP::template_t::getSimregions(), and ~simregion_t().
int UTAP::simregion_t::nr
Referenced by UTAP::cut_t::contains(), UTAP::cut_t::erase(), and UTAP::template_t::getSimregions().
update_t* UTAP::simregion_t::update
May be empty.
Referenced by UTAP::template_t::getSimregions(), and ~simregion_t().
The documentation for this struct was generated from the following files:
system.h
system.cpp