libutap: UTAP::template_t Struct Reference
UTAP::template_t Struct Reference
#include <system.h>
Public Member Functions
int addDynamicEval (expression_t t)
std::vector< expression_t > & getDynamicEval ()
state_t & addLocation (std::string, expression_t inv, expression_t er)
Add another location to template.
branchpoint_t & addBranchpoint (std::string)
Add another branchpoint to template.
edge_t & addEdge (symbol_t src, symbol_t dst, bool type, std::string actname)
Add edge to template.
instanceLine_t & addInstanceLine ()
Add another instance line to template.
message_t & addMessage (symbol_t src, symbol_t dst, int loc, bool pch)
Add message to template.
condition_t & addCondition (std::vector< symbol_t > anchors, int loc, bool pch, bool isHot)
Add condition to template.
update_t & addUpdate (symbol_t anchor, int loc, bool pch)
Add update to template.
bool isInvariant ()
return true if the LSC is of invariant mode
const std::vector< simregion_t > getSimregions ()
returns the simregions of an LSC scenario.
bool getCondition (instanceLine_t *instance, int y, condition_t *&simCondition)
gets the condition on the given instance, at y location, returns false if there isn't any
bool getUpdate (instanceLine_t *instance, int y, update_t *&simUpdate)
gets the update on the given instance at y location, returns false if there isn't any
bool getUpdate (const std::vector< instanceLine_t * > &instances, int y, update_t *&simUpdate)
Public Member Functions inherited from UTAP::instance_t
std::string writeMapping () const
std::string writeParameters () const
std::string writeArguments () const
Public Member Functions inherited from UTAP::declarations_t
bool addFunction (type_t type, std::string, function_t *&)
Add function declaration.
std::string toString (bool global=false) const
The following methods are used to write the declarations in an XML file.
std::string getConstants () const
std::string getTypeDefinitions () const
std::string getVariables (bool global) const
std::string getFunctions () const
Public Attributes
symbol_t init
The initial location.
frame_t templateset
Template set decls.
std::deque< state_t > states
Locations.
std::deque< branchpoint_t > branchpoints
Branchpoints.
std::deque< edge_t > edges
Edges.
std::vector< expression_t > dynamicEvals
bool isTA
std::deque< instanceLine_t > instances
Instance Lines.
std::deque< message_t > messages
Messages.
std::deque< update_t > updates
Updates.
std::deque< condition_t > conditions
Conditions.
std::string type
std::string mode
bool hasPrechart
bool dynamic
int dynindex
bool isDefined
Public Attributes inherited from UTAP::instance_t
symbol_t uid
The name.
frame_t parameters
The parameters.
std::map< symbol_t, expression_t > mapping
The arguments.
size_t arguments
size_t unbound
struct template_t * templ
std::set< symbol_t > restricted
Restricted variables.
Public Attributes inherited from UTAP::declarations_t
frame_t frame
std::list< variable_t > variables
Variables.
std::list< function_t > functions
Functions.
std::list< progress_t > progress
Progress measures.
std::list< iodecl_t > iodecl
std::list< gantt_t > ganttChart
Member Function Documentation
branchpoint_t & template_t::addBranchpoint (std::string)
Add another branchpoint to template.
References UTAP::branchpoint_t::bpNr, UTAP::Constants::BRANCHPOINT, UTAP::type_t::createPrimitive(), and UTAP::branchpoint_t::uid.
Referenced by UTAP::SystemBuilder::procBranchpoint().
condition_t & template_t::addCondition (std::vector< symbol_t > anchors, int loc, bool pch, bool isHot)
Add condition to template.
References UTAP::condition_t::nr.
int UTAP::template_t::addDynamicEval (expression_t t) inline
edge_t & template_t::addEdge (symbol_t src, symbol_t dst, bool type, std::string actname)
Add edge to template.
References edges, UTAP::symbol_t::getData(), UTAP::symbol_t::getType(), and UTAP::type_t::isLocation().
Referenced by UTAP::SystemBuilder::procEdgeBegin().
instanceLine_t & template_t::addInstanceLine ()
Add another instance line to template.
References UTAP::instanceLine_t::instanceNr.
Referenced by UTAP::SystemBuilder::procInstanceLine().
state_t & template_t::addLocation (std::string , expression_t inv, expression_t er)
Add another location to template.
References UTAP::type_t::createPrimitive(), UTAP::state_t::exponentialRate, UTAP::state_t::invariant, UTAP::Constants::LOCATION, UTAP::state_t::locNr, and UTAP::state_t::uid.
Referenced by UTAP::SystemBuilder::procState().
message_t & template_t::addMessage (symbol_t src, symbol_t dst, int loc, bool pch)
Add message to template.
References UTAP::symbol_t::getData(), and UTAP::message_t::nr.
Referenced by UTAP::SystemBuilder::procMessage().
update_t & template_t::addUpdate (symbol_t anchor, int loc, bool pch)
Add update to template.
References UTAP::symbol_t::getData(), and UTAP::update_t::nr.
Referenced by UTAP::SystemBuilder::procLscUpdate().
bool template_t::getCondition (instanceLine_t * instance, int y, condition_t *& simCondition)
gets the condition on the given instance, at y location, returns false if there isn't any
References UTAP::condition_t::anchors, UTAP::instanceLine_t::instanceNr, and UTAP::condition_t::location.
std::vector<expression_t>& UTAP::template_t::getDynamicEval () inline
References dynamicEvals.
const vector< simregion_t > template_t::getSimregions ()
returns the simregions of an LSC scenario.
A simregion is a simultaneous region containing 1 or 0 message, 1 or 0 update and 1 or 0 condition, at the same location. a message, update or condition must be in only one simregion.
we copy the messages, conditions and updates from the scenario
iterates over messages
we give priority to the condition on the target, if there is also one in the source, it must be part of another simregion
iterates over remaining conditions
iterates over remaining updates
References UTAP::condition_t::anchors, UTAP::simregion_t::condition, conditions_nr(), UTAP::message_t::dst, UTAP::message_t::location, UTAP::condition_t::location, UTAP::simregion_t::message, messages_nr(), UTAP::condition_t::nr, UTAP::update_t::nr, UTAP::simregion_t::nr, UTAP::simregion_t::setCondition(), UTAP::simregion_t::setMessage(), UTAP::simregion_t::setUpdate(), UTAP::message_t::src, UTAP::simregion_t::update, and updates_nr().
bool template_t::getUpdate (instanceLine_t * instance, int y, update_t *& simUpdate)
gets the update on the given instance at y location, returns false if there isn't any
References UTAP::update_t::anchor, UTAP::instanceLine_t::instanceNr, and UTAP::update_t::location.
bool UTAP::template_t::getUpdate (const std::vector< instanceLine_t * > & instances, int y, update_t *& simUpdate)
bool template_t::isInvariant ()
return true if the LSC is of invariant mode
Member Data Documentation
std::deque<branchpoint_t> UTAP::template_t::branchpoints
Branchpoints.
std::deque<condition_t> UTAP::template_t::conditions
Conditions.
bool UTAP::template_t::dynamic
Referenced by UTAP::TimedAutomataSystem::addDynamicTemplate(), UTAP::TimedAutomataSystem::addTemplate(), and UTAP::TypeChecker::checkExpression().
std::vector<expression_t> UTAP::template_t::dynamicEvals
Referenced by getDynamicEval().
int UTAP::template_t::dynindex
Referenced by UTAP::TimedAutomataSystem::addDynamicTemplate().
std::deque<edge_t> UTAP::template_t::edges
Edges.
Referenced by UTAP::XMLWriter::taTempl(), and UTAP::SignalFlow::visitProcess().
bool UTAP::template_t::hasPrechart
Referenced by UTAP::SystemBuilder::hasPrechart().
symbol_t UTAP::template_t::init
The initial location.
Referenced by UTAP::XMLWriter::init(), and UTAP::SystemBuilder::procStateInit().
std::deque<instanceLine_t> UTAP::template_t::instances
Instance Lines.
bool UTAP::template_t::isDefined
Referenced by UTAP::TimedAutomataSystem::addDynamicTemplate(), UTAP::TypeChecker::checkExpression(), UTAP::SystemBuilder::procBegin(), and UTAP::ExpressionBuilder::pushDynamicFrameOf().
bool UTAP::template_t::isTA
Referenced by UTAP::TimedAutomataSystem::addDynamicTemplate(), UTAP::TimedAutomataSystem::addTemplate(), and UTAP::XMLWriter::taTempl().
std::deque<message_t> UTAP::template_t::messages
Messages.
std::string UTAP::template_t::mode
Referenced by UTAP::TimedAutomataSystem::addTemplate().
std::deque<state_t> UTAP::template_t::states
Locations.
Referenced by UTAP::XMLWriter::taTempl(), and UTAP::SignalFlow::visitProcess().
frame_t UTAP::template_t::templateset
Template set decls.
std::string UTAP::template_t::type
Referenced by UTAP::TimedAutomataSystem::addTemplate().
std::deque<update_t> UTAP::template_t::updates
Updates.
The documentation for this struct was generated from the following files:
system.h
system.cpp