libutap: UTAP::instanceLine_t Struct Reference
UTAP::instanceLine_t Struct Reference
Information about an instance line.
#include <system.h>
Public Member Functions
std::vector< simregion_t > getSimregions (const std::vector< simregion_t > &simregions)
return the simregions anchored to this instance, ordered by location number
void addParameters (instance_t &inst, frame_t params, const std::vector< expression_t > &arguments)
Public Member Functions inherited from UTAP::instance_t
std::string writeMapping () const
std::string writeParameters () const
std::string writeArguments () const
Public Attributes
int32_t instanceNr
InstanceLine number in template.
Public Attributes inherited from UTAP::instance_t
symbol_t uid
The name.
frame_t parameters
The parameters.
std::map< symbol_t, expression_t > mapping
The arguments.
size_t arguments
size_t unbound
struct template_t * templ
std::set< symbol_t > restricted
Restricted variables.
Detailed Description
Information about an instance line.
Member Function Documentation
void instanceLine_t::addParameters (instance_t & inst, frame_t params, const std::vector< expression_t > & arguments)
References UTAP::frame_t::add(), UTAP::frame_t::getSize(), UTAP::instance_t::mapping, UTAP::instance_t::parameters, and UTAP::instance_t::templ.
Referenced by UTAP::SystemBuilder::instanceNameEnd().
vector< simregion_t > instanceLine_t::getSimregions (const std::vector< simregion_t > & simregions)
return the simregions anchored to this instance, ordered by location number
References UTAP::update_t::anchor, UTAP::condition_t::anchors, UTAP::message_t::dst, instanceNr, UTAP::message_t::nr, UTAP::condition_t::nr, UTAP::update_t::nr, and UTAP::message_t::src.
Member Data Documentation
int32_t UTAP::instanceLine_t::instanceNr
InstanceLine number in template.
Referenced by UTAP::template_t::addInstanceLine(), UTAP::template_t::getCondition(), getSimregions(), and UTAP::template_t::getUpdate().
The documentation for this struct was generated from the following files:
system.h
system.cpp