libutap: symbols.h File Reference
symbols.h File Reference
#include <inttypes.h>
#include <exception>
#include "utap/common.h"
#include "utap/position.h"
#include "utap/type.h"
Classes
class UTAP::NoParentException
class UTAP::range_t
An integer range.
class UTAP::symbol_t
A reference to a symbol.
class UTAP::frame_t
A reference to a frame.
Namespaces
UTAP
Functions
std::ostream & operator<< (std::ostream &o, UTAP::symbol_t t)
std::ostream & operator<< (std::ostream &o, UTAP::frame_t t)
Function Documentation
std::ostream& operator<< (std::ostream & o, UTAP::symbol_t t)
References UTAP::symbol_t::getName(), and UTAP::symbol_t::getType().
std::ostream& operator<< (std::ostream & o, UTAP::frame_t t)
References UTAP::frame_t::getSize().