libutap: system.cpp File Reference
system.cpp File Reference
#include <stack>
#include <algorithm>
#include <cstdio>
#include <climits>
#include <cassert>
#include <sstream>
#include <boost/bind.hpp>
#include "utap/builder.h"
#include "utap/system.h"
#include "utap/statement.h"
#include "libparser.h"
#include <string.h>
Functions
static deque< int > messages_nr (deque< message_t > messages)
static deque< int > conditions_nr (deque< condition_t > conditions)
static deque< int > updates_nr (deque< update_t > updates)
static void visit (SystemVisitor &visitor, frame_t frame)
Variables
static const char *const unsupported = "Internal error: Feature not supported in this mode."
static const char *const invalid_type = "$Invalid_type"
Function Documentation
static deque<int> conditions_nr (deque< condition_t > conditions) static
Referenced by UTAP::template_t::getSimregions().
static deque<int> messages_nr (deque< message_t > messages) static
Referenced by UTAP::template_t::getSimregions().
static deque<int> updates_nr (deque< update_t > updates) static
Referenced by UTAP::template_t::getSimregions().
static void visit (SystemVisitor & visitor, frame_t frame) static
References UTAP::Constants::BOOL, UTAP::Constants::CHANNEL, CLOCK, UTAP::Constants::DOUBLE, UTAP::Constants::FUNCTION, UTAP::type_t::getKind(), UTAP::frame_t::getSize(), UTAP::Constants::INSTANCELINE, UTAP::Constants::INT, UTAP::type_t::is(), LOCATION, UTAP::Constants::RECORD, UTAP::Constants::SCALAR, UTAP::type_t::stripArray(), UTAP::Constants::TYPEDEF, UTAP::SystemVisitor::visitFunction(), UTAP::SystemVisitor::visitInstanceLine(), UTAP::SystemVisitor::visitState(), UTAP::SystemVisitor::visitTypeDef(), and UTAP::SystemVisitor::visitVariable().
Referenced by UTAP::TimedAutomataSystem::accept().
Variable Documentation
const char* const invalid_type = "$Invalid_type" static
const char* const unsupported = "Internal error: Feature not supported in this mode." static