libutap: taflow.cpp File Reference
taflow.cpp File Reference
#include "utap/signalflow.h"
#include "utap/systembuilder.h"
#include "utap/typechecker.h"
#include "utap/system.h"
#include <iostream>
#include <fstream>
#include <string>
#include <inttypes.h>
#include <sys/param.h>
Functions
int getopt (int argc, char *const argv[], const char *optstring)
void printHelp (const char *binary)
int main (int argc, char *argv[])
Variables
char * optarg
int optind
int opterr
int optopt
Function Documentation
int getopt (int argc, char *const argv[], const char * optstring)
Referenced by main().
int main (int argc, char * argv[])
References UTAP::TimedAutomataSystem::accept(), UTAP::DistanceCalculator::addProcessNeedle(), UTAP::TimedAutomataSystem::getErrors(), getopt(), UTAP::TimedAutomataSystem::getWarnings(), optarg, optind, parseXMLFile(), parseXTA(), UTAP::Partitioner::partition(), UTAP::SignalFlow::printForDot(), UTAP::SignalFlow::printForTron(), printHelp(), and UTAP::SignalFlow::setVerbose().
void printHelp (const char * binary)
Referenced by main().
Variable Documentation
char* optarg
Referenced by main().
int opterr
int optind
Referenced by main().
int optopt