libutap: utap.h File Reference
utap.h File Reference
#include <cstdio>
#include "utap/common.h"
#include "utap/symbols.h"
#include "utap/expression.h"
#include "utap/system.h"
#include "utap/statement.h"
Functions
bool parseXTA (FILE *, UTAP::TimedAutomataSystem *, bool newxta)
bool parseXTA (const char *, UTAP::TimedAutomataSystem *, bool newxta)
int32_t parseXMLBuffer (const char *, UTAP::TimedAutomataSystem *, bool newxta)
int32_t parseXMLFile (const char *, UTAP::TimedAutomataSystem *, bool newxta)
UTAP::expression_t parseExpression (const char *, UTAP::TimedAutomataSystem *, bool)
int32_t writeXMLFile (const char *filename, UTAP::TimedAutomataSystem *taSystem)
Function Documentation
UTAP::expression_t parseExpression (const char * , UTAP::TimedAutomataSystem * , bool)
References UTAP::TypeChecker::checkExpression(), UTAP::ExpressionBuilder::getExpressions(), UTAP::TimedAutomataSystem::hasErrors(), parseXTA(), and UTAP::S_EXPRESSION.
int32_t parseXMLBuffer (const char * , UTAP::TimedAutomataSystem * , bool newxta)
References UTAP::TimedAutomataSystem::accept(), UTAP::TimedAutomataSystem::hasErrors(), and parseXMLBuffer().
Referenced by parseXMLBuffer().
int32_t parseXMLFile (const char * , UTAP::TimedAutomataSystem * , bool newxta)
References UTAP::TimedAutomataSystem::accept(), UTAP::TimedAutomataSystem::hasErrors(), and parseXMLFile().
Referenced by main(), and parseXMLFile().
bool parseXTA (FILE * , UTAP::TimedAutomataSystem * , bool newxta)
References UTAP::TimedAutomataSystem::accept(), UTAP::TimedAutomataSystem::hasErrors(), and parseXTA().
Referenced by parseExpression(), and parseXTA().
bool parseXTA (const char * , UTAP::TimedAutomataSystem * , bool newxta)
References UTAP::TimedAutomataSystem::accept(), UTAP::TimedAutomataSystem::hasErrors(), and parseXTA().
int32_t writeXMLFile (const char * filename, UTAP::TimedAutomataSystem * taSystem)
References UTAP::XMLWriter::project().