# Adds code coverage instrumentation to inspect the quality of tests
option(UTAP_COVERAGE "Enable UTAP Code Coverage" OFF)
set(UTAP_COVERAGE_TYPE "gcov" CACHE STRING "Coverage backend: gcov or llvm")
set_property(CACHE UTAP_COVERAGE_TYPE PROPERTY STRINGS gcov llvm)

add_library(coverage_config INTERFACE)

if(UTAP_COVERAGE)
    if (NOT UTAP_TESTS)
        message(WARNING "Code coverage is enabled while UTAP_TESTS is disabled")
    endif ()
    if(UTAP_COVERAGE_TYPE STREQUAL "llvm" AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        target_compile_options(coverage_config INTERFACE -fcoverage-mcdc -fprofile-instr-generate -fcoverage-mapping -O0 -g)
        target_link_options(coverage_config INTERFACE -fcoverage-mcdc -fprofile-instr-generate -fcoverage-mapping)
        message(STATUS "Enabled Code Coverage using llvm")
    else()
        target_compile_options(coverage_config INTERFACE --coverage -O0 -g)
        target_link_options(coverage_config INTERFACE --coverage)
        message(STATUS "Enabled Code Coverage using gcov")
    endif()
else ()
    message(STATUS "Disabled Code Coverage")
endif()

function(target_coverage target)
    if(UTAP_COVERAGE)
        target_link_libraries(${target} PRIVATE coverage_config)
    endif()
endfunction()
